const {JSDOM,VirtualConsole}=require('/workspace/scratch/078609482dd9/qa_runtime/node_modules/jsdom'),fs=require('fs'),assert=require('assert');
const errors=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.stack));const source=fs.readFileSync(__dirname+'/dist/index.html','utf8');
function boot(saved){return new JSDOM(source,{url:'https://mock.example',runScripts:'dangerously',virtualConsole:vc,beforeParse(w){w.structuredClone=structuredClone;w.confirm=()=>true;w.scrollTo=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};if(saved)w.localStorage.setItem('cian_confirmed_073538_revision_demo_v1',saved);}})}
const dom=boot(),w=dom.window,d=w.document,E=s=>w.eval(s);assert.deepEqual(errors,[]);assert.equal(E('OFFICIAL_TOPICS.filter(t=>t.verified).length'),100);assert.equal(E('OFFICIAL_TOPICS.filter(t=>t.researchRequired).length'),15);assert.equal(E('OFFICIAL_TOPICS[63].title'),'工房にはどんな道具がある？');
assert.deepEqual(Array.from(E('OFFICIAL_TOPICS.map(t=>t.title)')),fs.readFileSync(__dirname+'/official-themes.txt','utf8').trimEnd().split('\n'));assert(E('OFFICIAL_TOPICS.every(t=>!Object.hasOwn(t,"primaryAxis")&&!Object.hasOwn(t,"axes"))'));const p=E('demo.posts.find(p=>p.date===TODAY)'),id=p.id;assert.equal(p.briefId,'pattern');assert(p.caption.includes('型紙'));assert(!p.caption.includes('いつもの持ち物と合わせながら'));assert.equal(p.stories.length,4);assert(p.sequence.every(s=>p.shots.some(c=>c.id===s.shotId)));assert(p.stories.every(s=>s.materialMode==='過去素材使用可'||p.shots.some(c=>c.id===s.shotId)));assert.notEqual(p.stories[0].topicGroup,p.topicGroup);assert(!p.stories[2].skuIds.some(id=>p.skuIds.includes(id)));E('showPost('+JSON.stringify(id)+')');assert(d.querySelector('.stories-always'));assert(!d.querySelector('.stories-always').closest('details'));
const before=E('JSON.stringify(demo.posts.find(p=>p.id==='+JSON.stringify(id)+'))');E('monthCursor="2026-10";editSale()');const submit=()=>d.querySelector('#workForm').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));d.querySelector('#workForm').elements.date.value='2026-10-11';submit();assert.equal(E('JSON.stringify(demo.posts.find(p=>p.id==='+JSON.stringify(id)+'))'),before);
E('showPost('+JSON.stringify(id)+')');d.querySelector('#captionWork').value='手動本文';d.querySelector('[data-work-save-caption]').click();E('demo.conceptVersion=1;migrateConcepts()');assert.equal(E('demo.posts.find(p=>p.id==='+JSON.stringify(id)+').caption'),'手動本文');
E('editActual('+JSON.stringify(id)+')');let f=d.querySelector('#workForm');f.elements.actual.value=E('jstInput()');f.elements.theme.value='実際の型紙テーマ';f.elements.caption.value='実際に投稿した本文';f.elements.confirmed.checked=true;submit();assert(E('demo.posts.find(p=>p.id==='+JSON.stringify(id)+').actualSnapshot.caption')==='実際に投稿した本文');assert.equal(E('demo.posts.find(p=>p.id==='+JSON.stringify(id)+').caption'),'手動本文');assert(E('analysisPayload().posts.some(p=>p.theme==="実際の型紙テーマ")'));
const task=E('allTasks().find(t=>t.start<Date.now()).key');E('editRecord('+JSON.stringify(task)+')');f=d.querySelector('#workForm');assert.equal(f.querySelectorAll('input[type=number]').length,8);f.elements.views.value='0';f.elements.reach.value='';submit();assert.equal(E('demo.records['+JSON.stringify(task)+'].views'),0);assert.equal(E('demo.records['+JSON.stringify(task)+'].reach'),null);
E('go("analysis")');const a=JSON.parse(E('JSON.stringify(analysisSchema())'));assert.equal(E('validateImport('+JSON.stringify(JSON.stringify(a))+').schema'),2);a.trends=[{text:'誤った傾向',evidence:[a.facts[0].evidence[0]]}];assert.throws(()=>E('validateImport('+JSON.stringify(JSON.stringify(a))+')'));a.trends=[];a.proposals[0].changes.parentId='official-66';assert.throws(()=>E('validateImport('+JSON.stringify(JSON.stringify(a))+')'));a.proposals[0].changes.parentId=null;a.proposals[0].changes.topicGroup='INDUSTRY';a.proposals[0].changes.researchRequired=false;assert.throws(()=>E('validateImport('+JSON.stringify(JSON.stringify(a))+')'));
E('demo.planStart="2026-10-08"');const sale=E('createConcept("2026-10-10")');assert.equal(sale.primaryAxis,'BUSINESS');E('demo.posts.push(createConcept("2026-10-12"))');assert(E('createConcept("2026-10-13").primaryAxis')==='CUSTOMER_VALUE');assert(E('exportPrompt().includes("BUSINESS")&&exportPrompt().includes("newThemes")'));
E('demo.planStart=TODAY;go("analysis")');const incoming=JSON.parse(E('JSON.stringify(analysisSchema())'));incoming.batchId='apply-axis-test';incoming.newThemes=[{id:'extra-qa',parentId:'official-64',group:'CRAFT',title:'型紙の輪郭をたどる',evidence:incoming.facts[0].evidence}];const target=incoming.proposals[0].postId;E('demo.posts.find(p=>p.id==='+JSON.stringify(target)+').manual=true');d.querySelector('#analysisPaste').value=JSON.stringify(incoming);E('previewImport()');assert(!d.querySelector('[data-apply-proposal]').checked);d.querySelector('[data-apply-proposal]').checked=true;E('applyImport()');assert(E('demo.extraThemes.some(t=>t.id==="extra-qa")'));assert(E('demo.analyses.some(a=>a.batchId==="apply-axis-test")'));assert.throws(()=>E('validateImport('+JSON.stringify(JSON.stringify(incoming))+')'));const saved=E('JSON.stringify(demo)'),reload=boot(saved);assert.deepEqual(errors,[]);assert.equal(reload.window.eval('demo.posts.find(p=>p.id==='+JSON.stringify(id)+').caption'),'手動本文');console.log('PASS original preserved, topic provenance, theme-caption-story-shot coherence, Story visible, sale changes do not regenerate, manual migration protected, actual snapshot vs plan, 8 nullable metrics, schema2 validation, sale-aware roles, persistence');dom.window.close();reload.window.close();
