// Story・販売管理。既存ID・実績・手動編集を維持する追加層。
demo.salesHistory ||= [];
demo.salePlans ||= {};
if(!demo.storySalesVersion&&!demo.salesHistory.length){demo.salesHistory.push({id:'sale-history-demo-202605',date:'2026-05-10',time:'21:00',skuIds:demo.skus.slice(0,3).map(s=>s.id),sample:true,enteredAt:nowISO()});}
for(const m of Object.values(demo.months))for(const l of m.lineup)l.saleKind ||= sku(l.skuId)?.kind==='新作'?'新発売':sku(l.skuId)?.kind==='常時販売'?'常時販売':'再販';
function addMonths(month,n=4){const [y,m]=month.split('-').map(Number),d=new Date(Date.UTC(y,m-1+n,1));return d.toISOString().slice(0,7);}
function saleCycle(id){const history=demo.salesHistory.filter(h=>h.skuIds.includes(id)).sort((a,b)=>a.date.localeCompare(b.date));const last=history.at(-1)?.date;const suggested=last?addMonths(last.slice(0,7)):null;return {last,suggested,next:demo.salePlans[id]?.month||suggested,manual:!!demo.salePlans[id]?.month,history};}
function saleLine(id,date){return demo.months[date.slice(0,7)]?.lineup.find(l=>l.skuId===id);}
function effectiveSale(id,date){const m=demo.months[date.slice(0,7)],l=saleLine(id,date);return l?{...l,date:l.saleKind==='常時販売'?null:m.date,time:l.saleKind==='常時販売'?null:m.time}:null;}
function exposure(id,date){const s=sku(id),it=item(s.itemId);let n=0;for(const p of demo.posts.filter(p=>!p.deleted&&!p.paused&&p.date<date&&dayDiff(date,p.date)<=21)){const ids=[...(p.skuIds||[]),...(p.actualSnapshot?.stories||p.stories||[]).flatMap(x=>x.skuIds||[])];for(const x of ids){const t=sku(x);if(!t)continue;n+=x===id?4:t.itemId===s.itemId?1.5:item(t.itemId)?.categoryId===it.categoryId?0.5:0;if(s.material&&t.material===s.material)n+=.5;if(/black|noir|nero/i.test(s.name)&&/black|noir|nero/i.test(t.name))n+=.6;}}return n;}
function productScore(s,date){const l=effectiveSale(s.id,date),c=saleCycle(s.id);return (l?8:0)+(l?.priority?7:0)+(l?.saleKind==='新発売'?3:0)+(l?.saleKind==='常時販売'?1:0)+(l?.date&&dayDiff(l.date,date)>=0&&dayDiff(l.date,date)<=7?5:0)+(c.next===date.slice(0,7)?2:0)-exposure(s.id,date);}
const salesPlanContext=planContext;planContext=function(date){return {...salesPlanContext(date),date};};
const priorSelectSubjects=selectSubjects;selectSubjects=function(b,c){const initial=priorSelectSubjects(b,c);if(b.object!=='lineup')return initial;const date=c.date||TODAY;return demo.skus.filter(s=>!s.deleted&&saleLine(s.id,date)).sort((a,b)=>productScore(b,date)-productScore(a,date)).slice(0,3).map(s=>s.id);};
const STORY_KNOWLEDGE=[
 [9,'革の表と裏を見比べる','革の表側と裏側、同じ一枚でも表情が違います。表面の「銀面」と、繊維が見える裏側。手元の革小物にも、違いを探してみてください。','写真：革の表と裏を一緒に写した過去素材'],
 [35,'同じ革、その人らしい変化','同じ革でも、使う頻度や持ち方で変化は違います。誰かと同じ色に育たなくても大丈夫。自分が使ってきた時間として見比べるのも、革の楽しみです。','写真：使用期間が確認できる経年変化写真'],
 [45,'ケアの前に、革を確かめる','革のお手入れは、どれも同じではありません。まず素材と仕上げ、商品の案内を確認。迷ったら、使っているものの写真と一緒に相談してください。','写真：商品とケア案内の過去素材'],
 [64,'形になる前の型紙','工房の型紙は、革を切り出す形の目印。完成品と並べると、どの部分になるのか見えてきます。今日は形になる前の姿をひとつ。','写真：工房の型紙の過去素材'],
 [30,'動物の名前だけでは決まらない','同じ動物の革でも、部位や原皮、なめし、仕上げで表情は変わります。「牛革だから全部同じ」ではないところが、革選びの面白さです。','写真：由来を確認できる革見本の比較']
];
function storyHistory(date){return demo.posts.filter(p=>p.date<date&&!p.deleted&&!p.paused).sort((a,b)=>b.date.localeCompare(a.date)).flatMap(p=>(p.actualSnapshot?.stories||p.stories||[]).map(s=>({...s,date:p.date})));}
function makeStories(p){const history=storyHistory(p.date),last=history.find(s=>s.slot===1),pool=STORY_KNOWLEDGE.filter(k=>topicGroup(k[0])!==p.topicGroup&&topicGroup(k[0])!==last?.topicGroup);const k=(pool.length?pool:STORY_KNOWLEDGE).slice().sort((a,b)=>history.filter(s=>s.parentId==='official-'+a[0]).length-history.filter(s=>s.parentId==='official-'+b[0]).length)[0];
 const s1={slot:1,purpose:'知る・役立つ・楽しむ',parentId:'official-'+String(k[0]).padStart(2,'0'),topicGroup:topicGroup(k[0]),theme:k[1],text:k[2],asset:k[3],action:'手元の革と見比べる・話の種にする',skuIds:[],participatory:false,materialMode:'過去素材使用可'};
 const pending=demo.reactions.filter(r=>r.date<p.date&&!r.repliedAt&&((r.answers||[]).length||(r.dm||[]).length||(r.options||[]).some(o=>o.count>0))).sort((a,b)=>b.date.localeCompare(a.date)).find(r=>!history.some(s=>s.reactionId===r.id));
 const s2=pending?{theme:'いただいた反応への返答',text:'「'+pending.question+'」にお寄せいただいた声をご紹介します。\n'+[...(pending.options||[]).filter(o=>o.count!==null).map(o=>o.text+' '+o.count+'件'+((pending.options||[]).reduce((n,x)=>n+(x.count||0),0)>0?'（'+Math.round(o.count/(pending.options||[]).reduce((n,x)=>n+(x.count||0),0)*100)+'％）':'')),...(pending.answers||[]),...(pending.dm||[])].slice(0,3).join('\n')+'\nありがとうございます。次のご案内や、使いやすさを考える参考にします。',reactionId:pending.id,participatory:false}:{theme:'使う場面を聞く',text:dayDiff(p.date,'2026-01-01')%2?'革小物を使っていて、もっと知りたいことはありますか？ 手入れ・選び方・使い方など、ひとつ教えてください。':'財布を持って出かけるとき、どんな場面で使いにくさを感じますか？ 次のご案内の参考にさせてください。',participatory:true};Object.assign(s2,{slot:2,purpose:'参加・対話',asset:pending?'画像：記録した回答を文字で紹介（掲載許可を確認）':'写真：工房の過去素材に質問を重ねる',action:pending?'返答を読み、補足があればDMする':'質問スタンプで回答する',skuIds:[],materialMode:'過去素材使用可'});
 const mainItems=p.skuIds.map(id=>sku(id)?.itemId);let candidates=demo.skus.filter(s=>!s.deleted&&!mainItems.includes(s.itemId)).sort((a,b)=>productScore(b,p.date)-productScore(a,p.date));let reason='';if(!candidates.length){const c=salesContext(p.date);if(c.until!==null&&c.until<=3){candidates=p.skuIds.map(sku).filter(Boolean);reason='販売直前のため、当日の商品を再度紹介';}}
 const chosen=candidates.slice(0,1);if(chosen.length){const second=candidates.find(s=>s.id!==chosen[0].id&&s.itemId===chosen[0].itemId)||candidates.find(s=>s.itemId!==chosen[0].itemId);if(second)chosen.push(second);}
 const ids=chosen.map(s=>s.id),same=chosen.length>1&&chosen.every(s=>s.itemId===chosen[0].itemId);const s3={slot:3,purpose:'商品・革・ものづくりを発見',theme:same?'同じ形のカラー・素材比較':'持ち物の組み合わせ',combinationReason:same?'同じ形で、色・素材による見え方を比較する':'役割の違う革小物を、一緒に持つ場面で紹介する',text:ids.length?(same?'同じ形でも、色や素材で選ぶ楽しみがあります。':'いつもの持ち物に、こんな組み合わせはいかがでしょう。')+'\n'+ids.map(skuLabel).join('\n')+'\n気になる組み合わせはありますか？':'今日は裁断前の革を近くから。模様や表情を見比べてみてください。',asset:ids.length?'写真：対象商品を並べた商品写真・過去素材':'写真：裁断前の革の過去素材',action:'気になる商品があればDMで質問する',skuIds:ids,participatory:false,materialMode:'過去素材使用可',overlapReason:reason};
 const s4={slot:4,purpose:'今日のメイン投稿への導線',theme:p.theme,text:(p.hook||p.theme)+'\n'+(p.takeaway||'')+'\n'+(p.primaryAxis==='BUSINESS'?'対象商品と販売案内は、今日の投稿でご確認ください。':'今日の投稿で、写真や工程と一緒にご紹介しています。'),asset:'今日の投稿の表紙・Reelの切り出し',action:'今日のメイン投稿を開く',skuIds:[...p.skuIds],participatory:false,materialMode:'過去素材使用可',shotId:p.shots[0]?.id};return [s1,s2,s3,s4];}
const previousConcept=createConcept;createConcept=function(...args){const p=previousConcept(...args);p.stories=makeStories(p);p.storyVersion=3;p.combinationReason=p.skuIds.length>1?'今回のテーマに沿って、選び方・使う場面を比較する':'';return p;};
if(demo.storySalesVersion!==1){for(const p of demo.posts.slice().sort((a,b)=>a.date.localeCompare(b.date)))if(!p.manual&&!p.actualAt){p.stories=makeStories(p);p.storyVersion=3;}demo.storySalesVersion=1;}
function storyWarnings(p){const warnings=[];if(p.stories.filter(s=>s.participatory).length>1)warnings.push('参加型スタンプは原則1日1回です');const a=p.stories[0];if(a?.topicGroup===p.topicGroup)warnings.push('Story 1とメイン投稿が同じ分類です');const s=p.stories[2];if(s?.skuIds.some(id=>p.skuIds.some(x=>sku(x)?.itemId===sku(id)?.itemId))&&!s.overlapReason)warnings.push('Story 3の商品重複には理由を記録してください');return warnings;}
const storyShow=showPost;showPost=function(id){storyShow(id);const p=demo.posts.find(x=>x.id===id);dax('#dayDetail .story-card').forEach((el,i)=>{const s=p.stories[i];el.insertAdjacentHTML('beforeend',`<p class="tiny muted">${html((s.researchRequired?'要リサーチ · ':'')+(s.materialMode||'素材の準備を確認'))}${s.overlapReason?' · '+html(s.overlapReason):''}</p>${s.combinationReason?'<p class="tiny">組み合わせ：'+html(s.combinationReason)+'</p>':''}`);});const notes=storyWarnings(p);if(notes.length)dx('#dayDetail .stories-always').insertAdjacentHTML('afterbegin','<details><summary>重複の確認</summary>'+notes.map(x=>'<p>'+html(x)+'</p>').join('')+'</details>');};
function editStoryNew(id,index){const p=demo.posts.find(x=>x.id===id),s=p.stories[index];dx('#dayDialog').close();openForm('Story '+(index+1)+'｜'+s.purpose,`<label class="wlabel">実際に載せる文章<textarea name="text" rows="5">${html(s.text)}</textarea></label>`+formInput('使う写真・動画','asset',s.asset)+formInput('見た方にしてほしいこと','action',s.action)+formSelect('親テーマ（必要な場合）','parentId',[['','指定なし'],...OFFICIAL_TOPICS.map(t=>[t.id,t.group+' #'+t.number+' '+t.title])],s.parentId||'')+formSelect('素材の用意','materialMode',['過去素材使用可','新規撮影必要','まとめ撮り対象'],s.materialMode||'過去素材使用可')+`<details><summary>＋商品を追加・変更（最大8SKU）</summary>${skuPickerWork(s.skuIds)}</details>`+formInput('一緒に見せる理由','combinationReason',s.combinationReason||'')+formInput('メインと重ねる理由（重複する場合）','overlapReason',s.overlapReason||'')+`<label class="pick-name"><input name="participatory" type="checkbox" ${s.participatory?'checked':''}>参加型スタンプを使う</label>`,f=>{const ids=f.getAll('skuIds');if(ids.length>8)throw Error('1企画は8SKUまで選択してください');if(/\p{Extended_Pictographic}/u.test(f.get('text'))||/星占い|星座占い/.test(f.get('text')))throw Error('Storyに絵文字は使いません');if(f.has('participatory')&&p.stories.some((t,i)=>i!==index&&t.participatory))throw Error('参加型スタンプは1日1回までです');if(index===2&&ids.some(x=>p.skuIds.some(y=>sku(x)?.itemId===sku(y)?.itemId))&&!f.get('overlapReason').trim())throw Error('商品が重複する理由を記録してください');Object.assign(s,{text:f.get('text'),asset:f.get('asset'),action:f.get('action'),skuIds:ids,materialMode:f.get('materialMode'),combinationReason:f.get('combinationReason'),overlapReason:f.get('overlapReason'),participatory:f.has('participatory'),manual:true,parentId:f.get('parentId')||null,topicGroup:OFFICIAL_TOPICS.find(t=>t.id===f.get('parentId'))?.group||null,researchRequired:['INDUSTRY','FASHION'].includes(OFFICIAL_TOPICS.find(t=>t.id===f.get('parentId'))?.group)});delete s.shotId;p.manual=true;p.revision++;});}
document.addEventListener('click',e=>{const b=e.target.closest('[data-work-story]');if(b){e.stopImmediatePropagation();const [id,i]=b.dataset.workStory.split('|');editStoryNew(id,+i);}},true);
function salePickerFilters(){return `<div class="metrics-grid">${formSelect('絞り込み','saleFilter',[['all','すべて'],['candidate','今月販売候補'],['next','次回販売月が今月'],['soldout','SOLD OUT'],['always','常時販売'],['selected','今月対象']],'all')}${formSelect('カテゴリ','saleCategory',[['','すべて'],...demo.categories.filter(c=>!c.deleted).map(c=>[c.id,c.name])],'')}</div>`;}
editSale=function(){const m=monthInfo(monthCursor);openForm(monthCursor+'の販売対象',formInput('オンライン販売日','date',m.date,'date')+formInput('販売開始','time',m.time,'time')+'<p class="tiny muted">新発売・再販は上の日時を共通で使います。チェックは今月対象、販売状態は現在の状態です。</p>'+salePickerFilters()+skuPickerWork(m.lineup.map(l=>l.skuId),true),f=>{const date=f.get('date');if(date&&date.slice(0,7)!==monthCursor)throw Error('表示中の月の販売日を入力してください');const ids=f.getAll('skuIds'),lines=ids.map(id=>({...m.lineup.find(l=>l.skuId===id),skuId:id,saleKind:f.get('kind-'+id)||'再販'}));if(lines.some(l=>l.saleKind!=='常時販売')&&!date)throw Error('新発売・再販の共通販売日を入力してください');const statuses=demo.skus.map(s=>({s,status:f.get('status-'+s.id),restock:f.get('restock-'+s.id)})).filter(x=>x.status);for(const x of statuses){const l=lines.find(l=>l.skuId===x.s.id);if(x.status==='restock'&&!x.restock&&!(l&&l.saleKind!=='常時販売'&&date))throw Error('再販予定の日付を設定してください');}for(const x of statuses){x.s.status=x.status;const l=lines.find(l=>l.skuId===x.s.id);if(x.status==='restock')x.s.restockDate=l&&l.saleKind!=='常時販売'?date:x.restock;else x.s.restockDate='';}for(const l of lines)if(!m.lineup.some(old=>old.skuId===l.skuId)&&l.saleKind!=='常時販売')demo.salePlans[l.skuId]={month:monthCursor,updatedAt:nowISO()};m.date=date;m.time=f.get('time');m.lineup=lines;});
 const form=dx('#workForm');for(const row of dax('#workForm .picker-sku')){const id=row.querySelector('[name=skuIds]').value,l=m.lineup.find(l=>l.skuId===id),c=saleCycle(id);row.dataset.sku=id;row.insertAdjacentHTML('beforeend',`<div class="sale-line-options" ${l?'':'hidden'}>${formSelect('今月の販売区分','kind-'+id,['新発売','再販','常時販売'],l?.saleKind||'再販')}<p class="tiny sale-date-hint"></p></div><p class="tiny muted">前回：${c.last?short(c.last):'未記録'} · 次回${c.manual?'予定':'目安'}：${html(c.next||'未設定')}</p><p class="tiny cycle-warning"></p>`);}
 function update(){const mode=form.elements.saleFilter.value,cat=form.elements.saleCategory.value,q=form.querySelector('.picker-search').value.toLowerCase();for(const row of form.querySelectorAll('.picker-sku')){const id=row.dataset.sku,s=sku(id),c=saleCycle(id),checked=row.querySelector('[name=skuIds]').checked,kind=row.querySelector('[name="kind-'+id+'"]').value;row.querySelector('.sale-line-options').hidden=!checked;row.querySelector('.sale-date-hint').textContent=kind==='常時販売'?'販売日に固定しません':(form.elements.date.value||'販売日を登録')+' '+form.elements.time.value+' を共通で使用';const matches=mode==='all'||mode==='candidate'&&(c.next===monthCursor||checked)||mode==='next'&&c.next===monthCursor||mode==='soldout'&&s.status==='soldout'||mode==='always'&&kind==='常時販売'||mode==='selected'&&checked;row.hidden=!(matches&&(!cat||item(s.itemId).categoryId===cat)&&row.dataset.search.includes(q));row.querySelector('.cycle-warning').textContent=checked&&c.suggested&&monthCursor<c.suggested?'標準の4か月サイクルより早い設定です。登録できます。':'';const ri=row.querySelector('[name="restock-'+id+'"]');if(checked&&kind!=='常時販売'){ri.hidden=true;ri.value=form.elements.date.value;} }
 for(const el of form.querySelectorAll('.picker-item,.picker-cat')){el.hidden=![...el.querySelectorAll('.picker-sku')].some(r=>!r.hidden);if(mode!=='all'||q||cat)el.open=!el.hidden;}form.querySelector('.pick-count').textContent=form.querySelectorAll('[name=skuIds]:checked').length+'SKU選択';}
 form.addEventListener('input',update);form.addEventListener('change',update);form.addEventListener('click',()=>queueMicrotask(update));update();};
editSkuWork=function(id,iid){const s=sku(id)||{id:newId(),itemId:iid,name:'',material:'',status:'soldout',restockDate:''},c=saleCycle(s.id);openForm('カラー・素材',formInput('カラー／バリエーション名','name',s.name,'text',true)+formInput('素材名','material',s.material)+formSelect('現在の販売状態','status',[['restock','再販予定'],['selling','販売中'],['soldout','SOLD OUT']],s.status)+`<div id="restockWork" ${s.status==='restock'?'':'hidden'}>${formInput('再販予定日','restockDate',s.restockDate,'date')}</div><p class="tiny">前回：${html(c.last||'未記録')} · 自動の次回目安：${html(c.suggested||'実績の登録後に計算')}</p>`+formInput('次回販売月（必要なときだけ変更）','nextMonth',demo.salePlans[s.id]?.month||'','month')+`<p class="tiny muted">空欄なら前回販売から4か月。手動変更した月は自動で戻しません。</p><details><summary>実際の販売履歴</summary>${c.history.map(h=>'<p>'+html(h.date)+' '+html(h.time||'')+'</p>').join('')||'<p>実際の販売履歴はまだありません。</p>'}</details>`,f=>{if(!String(f.get('name')).trim())throw Error('名称を入力してください');if(f.get('status')==='restock'&&!f.get('restockDate'))throw Error('再販予定日を入力してください');Object.assign(s,{name:f.get('name'),material:f.get('material'),status:f.get('status'),restockDate:f.get('restockDate')});demo.salePlans[s.id]={month:f.get('nextMonth')||null,updatedAt:nowISO()};if(!id)demo.skus.push(s);},id?()=>{s.deleted=true;s.discontinuedAt=nowISO();}:null);dx('#workForm [name=status]').onchange=e=>dx('#restockWork').hidden=e.target.value!=='restock';if(id)dx('#workDelete').textContent='非表示・廃番にする';};
function recordSale(){const m=monthInfo(monthCursor);openForm('実際の販売を記録',formInput('実際の販売日','actualDate',m.date,'date',true)+formInput('実際の開始時刻','actualTime',m.time,'time')+'<p class="tiny muted">登録した販売予定から引き継ぎます。実際に販売した対象だけチェックしてください。予定と履歴は別に保存します。</p>'+skuPickerWork(m.lineup.map(l=>l.skuId)),f=>{const ids=f.getAll('skuIds'),date=f.get('actualDate');if(!ids.length)throw Error('販売した商品を選択してください');if(date>TODAY)throw Error('未来の日付は販売実績にできません');if(demo.salesHistory.some(h=>h.date===date&&h.skuIds.some(id=>ids.includes(id))))throw Error('同じ日・商品の販売実績が登録されています');demo.salesHistory.push({id:newId(),date,time:f.get('actualTime'),skuIds:ids,lineup:ids.map(id=>({...m.lineup.find(l=>l.skuId===id),skuId:id})),enteredAt:nowISO()});});}
const salesMonthRender=renderMonthWork;renderMonthWork=function(){salesMonthRender();dax('#monthSavedWork .priorityline').forEach((el,i)=>{const l=monthInfo(monthCursor).lineup[i];el.querySelector('small').textContent=l?.saleKind||'再販';});dx('#monthSavedWork').insertAdjacentHTML('beforeend',`<details><summary>販売履歴・次回の目安</summary><button class="secondary full" id="recordSaleNew">実際に販売した対象を記録</button><p class="tiny muted">予定を保存しただけでは、販売実績にはなりません。</p>${demo.salesHistory.slice().reverse().map(h=>`<p>${html(h.date)} · ${h.skuIds.length}SKU${h.sample?'（仮データ）':''}</p>`).join('')||'<p>実績はまだ未登録です。</p>'}</details>`);};
const salesCatalog=renderCatalog;renderCatalog=function(){salesCatalog();dax('#catalogListWork [data-work-sku]').forEach(el=>{const c=saleCycle(el.dataset.workSku);el.insertAdjacentHTML('beforeend',`<small>前回：${c.last?short(c.last):'未記録'} · 次回${c.manual?'予定':'目安'}：${html(c.next||'未設定')}</small>`);});};
document.addEventListener('click',e=>{if(e.target.closest('#recordSaleNew'))recordSale();});
function specificShootDirections(p){if(p.manual||p.actualAt)return p.shots;const topic=OFFICIAL_TOPICS.find(t=>t.id===p.parentId),products=p.skuIds.map(skuLabel).join('・')||p.subjects||'テーマに使う実物',materials=p.skuIds.map(id=>sku(id)?.material).filter(Boolean).join('・'),stories=(p.stories||[]).map(s=>[s.theme,s.text,s.asset].filter(Boolean).join(' ')).join(' '),mainSource=[topic?.title,p.derivedTheme,p.theme,p.takeaway,p.caption,products,materials].filter(Boolean).join(' '),source=mainSource+' '+stories,moving=p.format==='Reel',media=moving?'動画':'写真',directions=/型紙/.test(mainSource)?['型紙の全体と、対応する革・裁断道具を真上から一画面に収める','革の上へ型紙を置き、輪郭を合わせる手元から裁断直前までを寄りで撮る','裁断前の平らな革、切り出したパーツ、組み上がる途中の順に並べて形の変化を見せる']:/クリーム|塗りすぎ/.test(mainSource)?['同じ革の端材を二枚用意し、片方は適量、片方は多めのクリーム量が見えるよう真上から撮る','指先または布に取ったクリーム量と、薄く伸ばす手元を接写する','塗布前・適量塗布後・多量塗布後を同じ光と角度で並べ、艶や色の差を撮る']:/お客様の声|改良/.test(mainSource)?['お客様の声の要点を書いたメモと、該当する商品箇所を同じ画面に置く','要望に関係する収納部・開閉部・サイズを手で示し、現状が分かる距離で撮る','現行仕様と検討中の改善箇所を同じ角度で並べ、違いを指差して撮る']:/購入した後|使った後/.test(mainSource)?['対象商品を手に取るところから、開く・収納する・閉じるまでを使用順に撮る','毎日触れる角・折り曲げ部・金具を寄りで撮り、使い始めに見る箇所を示す','使用後に置く場所と乾拭きする手元を撮り、購入後の扱いを一続きで見せる']:/お得/.test(mainSource)?['価格だけでなく、縫い目・コバ・金具が分かる商品全体を正面から撮る','カードや小銭を入れ、毎日使う動作と収納量が分かる手元を撮る','新品と長期使用例を同じ角度で並べ、使った期間と変化箇所を示す']:/長く使/.test(mainSource)?['乾いた布・ブラシ・対象の革製品を並べ、日常の手入れ道具を真上から撮る','縫い目・コバ・曲げ部分を順に寄り、傷みを早めに確認する箇所を撮る','乾拭き前後を同じ光で撮り、保管時に形を整える手元まで見せる']:/ブランド/.test(mainSource)?['作業台に革・型紙・完成品を並べ、ブランドが扱う素材から仕立てまでを一画面で見せる','対象商品を手に持ち、サイズ感と革の表情が同時に分かる距離で撮る','Storyの問いに対応する選択肢を、商品・工程・接客メモの三場面で撮る']:/これから|変わっていく/.test(mainSource)?['現在使われている革小物と、これから試したい形・素材見本を横に並べる','手持ち・バッグ収納・机上の三場面で、今後も必要になる使い方を撮る','革の表情、修理できる箇所、交換しやすい部位へ順に寄り、長く残せる作りを示す']:/流行/.test(mainSource)?['過去・現在を想定した二つの持ち物セットを同じ背景に組み、違いを真上から撮る','対象商品を服装の色だけ変えて持ち、流行に左右される部分と合わせやすい部分を撮る','短期で変わる装いと、使い続けた革の表情を同じ画角で対比する']:p.topicGroup==='CRAFT'?['使用する道具と革を工程順に並べ、名称と位置が分かる真上の画を撮る','本文で扱う工程を、開始前・作業中の手元・完了直後の三段階で撮る','完成品の該当箇所へ寄り、直前の工程がどこに表れているか指で示す']:p.topicGroup==='CARE'?['対象の革と使用するケア道具を並べ、量と種類が分かるよう撮る','手入れ前の表面、作業中の手元、手入れ後を同じ光と角度で撮る','本文とStoryで触れる注意箇所へ寄り、避ける状態と適切な状態を比較する']:['投稿テーマに関係する'+products+'を正面・真上・手持ちの三方向から撮る','本文の中心となる「'+(p.takeaway||p.derivedTheme||p.theme)+'」が分かる箇所へ寄り、手で示す','Storyで使う問いや比較に合わせ、'+products+'を同じ光と背景で並べて差を撮る'];return directions.map((what,i)=>{const original=p.shots[i]||{};return {...original,id:original.id||p.id+'-specific-'+i,signature:original.signature||['specific',p.id,i].join('|'),media,what:(moving?i===0?'冒頭から3秒：':i===1?'続きの動き：':'締めの比較：':(i+1)+'枚目：')+what+(materials?'（素材：'+materials+'）':''),skuIds:i===0&&/型紙/.test(mainSource)?[]:[...p.skuIds],count:1};});}
const oldStoryShootGroups=shootGroups;shootGroups=function(){const groups=new Map();for(const p of rangePosts().filter(p=>!p.paused&&!p.deleted&&!blocked(p.date))){const shots=[...specificShootDirections(p),...p.stories.filter(s=>s.materialMode!=='過去素材使用可'&&(!s.shotId||!p.shots.some(c=>c.id===s.shotId))).map(s=>({signature:'story|'+s.asset+'|'+s.skuIds.slice().sort().join('|'),what:s.asset,media:/動画/.test(s.asset)?'動画':'写真',skuIds:s.skuIds,count:1}))];for(const shot of shots){const key=shot.signature||[shot.media,shot.what,...shot.skuIds.slice().sort()].join('|');if(!groups.has(key))groups.set(key,{...shot,signature:key,uses:[]});groups.get(key).uses.push({id:p.id,date:p.date});}}return [...groups.values()];};
const salesRenderShoot=renderShoot;renderShoot=function(){const cuts=shootGroups(),indexed=cuts.map((c,i)=>({c,i})),total=cuts.reduce((n,c)=>n+c.count,0),done=cuts.filter(c=>demo.shotDone[c.signature]).reduce((n,c)=>n+c.count,0),posts=rangePosts().filter(p=>!p.paused&&!p.deleted&&!blocked(p.date)).sort((a,b)=>a.date.localeCompare(b.date));dx('#shootProgressBadge').textContent=done+' / '+total+'必須カット';dx('#shootList').innerHTML=posts.map(p=>{const daily=indexed.filter(x=>x.c.uses.some(u=>u.id===p.id));if(!daily.length)return '';return `<article class="card shoot-group shoot-day"><div class="section-kicker">${html(planDay(p.date))}</div><h3>${html(p.derivedTheme||p.theme)}</h3>${daily.map(({c,i})=>`<div class="shoot-item"><input type="checkbox" aria-label="${html(c.what)}" data-work-shot="${i}" ${demo.shotDone[c.signature]?'checked':''}><label><strong>${html(c.media)} · ${c.count}カット</strong><div>${html(c.what)}</div><div class="exact muted tiny">${html(c.skuIds.map(skuLabel).join(' ＋ ')||'商品紹介以外')}</div></label></div>`).join('')}</article>`;}).join('')||'<article class="card">対象期間の撮影はありません。</article>';const sets=new Map();cuts.forEach(c=>{const key=c.media+'｜'+(/工房|道具|型紙|裁断|縫/.test(c.what)?'工房・作業台':'商品・革の比較');if(!sets.has(key))sets.set(key,[]);sets.get(key).push(c);});dx('#shootList').insertAdjacentHTML('beforeend',`<details class="card"><summary>撮影セットにまとめて準備</summary>${[...sets].map(([key,cs])=>`<h3>${html(key)}</h3><p class="exact">${html([...new Set(cs.flatMap(c=>c.skuIds))].map(skuLabel).join(' ＋ ')||'道具・革見本')}</p><p class="tiny">${[...new Set(cs.flatMap(c=>c.uses.map(u=>planDay(u.date))))].join(' / ')}</p><p class="tiny">${cs.length}種類のカット。セットは共通、異なる構図は個別に撮影。</p>`).join('')}</details><details class="card"><summary>過去素材で準備できるStory</summary>${posts.flatMap(p=>p.stories.filter(s=>s.materialMode==='過去素材使用可').map(s=>`<p>${planDay(p.date)} · ${html(s.purpose)}<br>${html(s.asset)}<br>${html(s.skuIds.map(skuLabel).join(' ＋ '))}</p>`)).join('')}<p class="tiny muted">指定の素材があるか確認し、なければStory編集で「まとめ撮り対象」に変更してください。</p></details>`);};
const salesHome=renderHome;renderHome=function(){salesHome();const p=demo.posts.find(p=>p.date===TODAY&&!p.paused&&!p.deleted);if(p)dx('#homeStoryPreview p').textContent=p.stories[0]?.text||'';};
const salesResults=renderResults;renderResults=function(){salesResults();const grouped=new Map();for(const r of demo.reactions){const key=r.theme||r.question;if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(r);}const repeated=[...grouped].filter(([k,rs])=>rs.length>1);if(repeated.length)dx('#reactionListWork').insertAdjacentHTML('beforeend','<details class="card"><summary>繰り返し届くテーマ</summary>'+repeated.map(([k,rs])=>'<p>'+html(k)+' · '+rs.length+'記録<br>メイン投稿・商品サービス改善の候補</p>').join('')+'<p class="tiny muted">記録件数です。人数や需要の規模とは区別して判断します。</p></details>');};
const salesPayload=analysisPayload;analysisPayload=function(){const data=salesPayload();return {...data,salesHistory:demo.salesHistory,salePlans:demo.salePlans,storyHistory:demo.posts.filter(p=>p.date>=analysisFrom&&p.date<=analysisTo).map(p=>({postId:p.id,date:p.date,stories:p.actualSnapshot?.stories||p.stories,status:p.actualSnapshot?'実績':'予定'})),storyGuidance:'Storyは知識・参加対話・別商品発見・メイン導線の4枠。反応への返答を優先。好反応の知識は後日のメイン候補へ。声は情報発信と商品サービス改善へ。商品露出と販売周期を参考にし、3軸の固定比率を設けない。',saleCycleRule:'実際の販売から4か月が目安。手動予定を優先し、早期再販も許可。'};};
const salesMeta=editPostMeta;editPostMeta=function(id){salesMeta(id);const p=demo.posts.find(p=>p.id===id),oldIds=[...p.skuIds],form=dx('#workForm'),save=form.onsubmit;form.querySelector('.save-foot').insertAdjacentHTML('beforebegin',formInput('複数商品を一緒に見せる理由','combinationReason',p.combinationReason||''));form.onsubmit=e=>{const f=new FormData(e.target);if(f.getAll('skuIds').length>8){e.preventDefault();dx('#workError').textContent='1企画は8SKUまで選択してください';return;}save(e);if(!dx('#workDialog').open){p.combinationReason=f.get('combinationReason');for(const shot of p.shots)if(shot.skuIds.length&&shot.skuIds.every(id=>oldIds.includes(id))){shot.skuIds=[...p.skuIds];shot.signature=[shot.media,shot.what,...shot.skuIds.slice().sort()].join('|');}const guide=p.stories.find(s=>s.slot===4);if(guide&&!guide.manual)guide.skuIds=[...p.skuIds];persist();}};};
const saleReactionEdit=editReaction;editReaction=function(id){saleReactionEdit(id);const r=demo.reactions.find(r=>r.id===id),form=dx('#workForm'),save=form.onsubmit;form.querySelector('.save-foot').insertAdjacentHTML('beforebegin','<label class="pick-name"><input type="checkbox" name="replied" '+(r?.repliedAt?'checked':'')+'>この反応への返答を掲載済み</label>');form.onsubmit=e=>{const f=new FormData(e.target),before=demo.reactions.length;save(e);if(!dx('#workDialog').open){const target=id?demo.reactions.find(r=>r.id===id):demo.reactions[before];if(target){target.repliedAt=f.has('replied')?(target.repliedAt||nowISO()):null;persist();}}};};
document.head.insertAdjacentHTML('beforeend','<style>.sale-line-options{padding:8px;background:#f1f3f1;border-radius:8px}.cycle-warning{color:#844323}.picker-sku[hidden],.sale-line-options[hidden]{display:none!important}.picker-sku select{max-width:100%}.story-card .tiny{font-size:14px}#workForm .picker-list{max-height:55vh;overflow:auto}#catalogListWork .eventline small{display:block}button,input,select{min-height:44px}</style>');
persist();refreshWork();
