// 3軸の企画層。既存の投稿ID・商品ID・手動編集・実績を維持する。
const AXES={CUSTOMER_VALUE:'CUSTOMER VALUE｜お客様への価値',INSTAGRAM_GROWTH:'INSTAGRAM GROWTH｜届ける力',BUSINESS:'BUSINESS｜ブランドを続ける力'};
const axisShort={CUSTOMER_VALUE:'楽しむ・知る・役立つ',INSTAGRAM_GROWTH:'新しい人に届ける',BUSINESS:'商品・販売・信頼'};
const topicGroup=n=>n<=20?'LEATHER':n<=30?'ANIMAL':n<=40?'AGING':n<=50?'CARE':n<=65?'CRAFT':n<=80?'INDUSTRY':n<=90?'FASHION':'CUSTOMER';
const OFFICIAL_TOPIC_TITLES=["そもそも「革」とは何なのか", "革になる前の「原皮」はどんな状態なのか", "毛を取った直後の革は驚くほど重い", "なぜ革には大量の水が必要なのか", "「なめし」とは何をしているのか", "タンニンなめしとクロムなめしの違い", "同じ牛革でも、なぜ全く違う革になるのか", "革の「厚み」はどうやって決まる？", "革の表面にある「銀面」とは？", "革の裏側はなぜ毛羽立っているのか", "革の「コシ」とは何なのか", "革が柔らかい＝良い革、ではない理由", "革の傷は「悪い革」なのか", "同じ黒でも革によって色が違って見える理由", "革の匂いは何の匂いなのか", "革によって水への強さが違う理由", "革の表面加工には何がある？", "顔料仕上げと染料仕上げの違い", "「革の個体差」が生まれる理由", "良い革・悪い革をどう判断するのか", "牛革の特徴", "馬革の特徴", "山羊革の特徴", "羊革の特徴", "牛革と馬革、何が違う？", "山羊革は財布に向いている？特徴と使いやすさ", "羊革が驚くほど柔らかい理由", "コードバンは普通の馬革と何が違う？", "クロコダイル革はなぜ高い？", "同じ動物でも革の表情が違う理由", "革はなぜ使うと色が変わるのか", "革が「艶」を持つ理由", "経年変化する革・しにくい革", "良い経年変化とは何なのか", "同じ革でも使う人によって変化が違う", "毎日使う財布はどれくらい変化する？", "新品と1年使用後の革を比較", "3年使った革はどうなる？", "傷は消える？残る？", "「育てる革」を選ぶという考え方", "革財布は毎日メンテナンスするべき？", "革にクリームを塗りすぎるとどうなる？", "水に濡れた革、まず何をする？", "革にやってはいけないこと5選", "革の種類によってケア方法は違う", "財布を長く使うためにできること", "革のクリームは何を基準に選ぶ？", "メンテナンスしない方がいい革もある？", "使い込んだ財布を職人が見てみる", "財布を長く使うために必要なこと", "財布が完成するまで", "革を裁断する瞬間", "革のどこを使うかはどう決める？", "革の傷を見て裁断位置を決める", "革を漉く「ベタ漉き」とは？", "なぜ革を薄くする必要がある？", "ミシンで革を縫う難しさ", "職人が見る「縫い目」のポイント", "財布の角を綺麗に仕上げる理由", "同じ財布でも職人によって仕上がりが違う", "タンナーと革職人の仕事の違い", "タンナーによって革の個性が変わる", "革職人が朝一番にすること", "工房にはどんな道具がある？", "職人が「良い革」と感じる瞬間", "日本の革産業は今どうなっている？", "なぜ日本のタンナーは減っているのか", "革職人の後継者問題", "革産業の人手不足と外国人労働者の現状", "革産業と水の問題", "革づくりに使われる薬品はどこから来る？", "サステナブルな革とは何なのか", "「環境に優しい革」は本当に環境に優しい？", "革製品の価格は生産国によってなぜ違う？", "革の価格は何で決まる？", "高価格帯ブランドで使われる革は何が違う？", "同じように見える革製品でも、ブランドによって価格が違う理由", "革はどこから日本に入ってくる？", "日本の革づくりは海外でどう評価されている？", "革産業の未来に必要なもの", "今日の革・ファッションニュース", "今季注目されている素材", "最近増えているバッグの形", "今、財布はどう変化している？", "キャッシュレス時代に革財布はどうなる？", "なぜ今「長く使う」が注目されるのか", "ファストファッションのメリット・デメリット", "流行のサイクルが速くなった理由", "「高いものを長く使う」は本当にお得？", "これから革製品はどう変わっていく？", "お客様から一番多い革の質問", "「どの革を選べばいい？」に職人が答える", "お客様の財布を見せてもらう", "何年も使っている財布を見せてもらう", "修理で戻ってきた財布を見る", "お客様の使い方から新しい発見", "「こんな財布が欲しい」を聞いてみる", "お客様の声から商品を改良する", "財布を購入した後、どう使ってほしいか", "cian en paclamをどんなブランドにしてほしい？"];
const OFFICIAL_TOPICS=OFFICIAL_TOPIC_TITLES.map((title,i)=>Object.freeze({id:"official-"+String(i+1).padStart(2,"0"),number:i+1,group:topicGroup(i+1),title,verified:true,source:"ユーザー提供の正式100テーマ原文",researchRequired:i>=65&&i<80,knowledgeStatus:i>=65&&i<80?"要リサーチ":"投稿制作時に根拠・実物を確認"}));
const BRIEFS=[
 {id:'pattern',parentId:'official-64',group:'CRAFT',title:'型紙は何に使う？',message:'平らな型紙から革を切り出し、立体の財布になる流れを楽しむ。',role:'製作背景',object:'mini',preferred:'Reel',scenes:[['作業台に置いた型紙の端だけを見せる','この紙、何に使うと思いますか？',false],['型紙の全体を真上から見せる','ヒント：革を切る前に使います。',false],['革の上に型紙を重ね、同じ部品を切り出す手元','答えは型紙。革の部品の形を決めるために使います。',false],['切り出した部品と対応する完成品を同じ画角に置く','平らな部品が、こんな形に。今日の投稿で続きをどうぞ。',true]],paragraphs:[
 'この紙、何に使うと思いますか？\n\n今日は、完成した財布の少し手前にある「型紙」の話です。お店の写真では完成品を見ることが多いですが、工房では、まだ立体になっていない形と向き合う時間があります。財布になる前の姿を知ると、いつも見ている形も少し違って見えるかもしれません。',
 '型紙は、革から切り出す部品の形を決めるためのものです。写真の紙を革の上に置くと、どこを、どんな形に切るのかが見えてきます。今日は「紙だけ」「革に重ねたところ」「切り出した部品」「完成品」の順に並べました。最初に答えを読まず、どの部分になりそうか想像してから見るのもおすすめです。',
 '平らな紙だけを見ると、これが財布のどこになるのだろう、と不思議に感じるかもしれません。折り曲げたり、別の部品と組み合わせたりすると、完成したときの形へ近づいていきます。外から見えている輪郭と、部品一枚の輪郭が、そのまま同じとは限らないところも面白いところです。',
 '型紙があれば、あとは切るだけ、と思われることもあるかもしれません。でも、実際の革に重ねたところを見ると、紙では分からなかった表面の表情が一緒に見えてきます。今回は同じ部品を追いかけて撮るので、途中で違う財布の工程にならないよう、完成品までつながる順番で見ていただけます。',
 'ものづくりの道具というと、刃物やミシンのようなものが目を引きますよね。そのそばにある型紙も、形をつくるための大切な存在です。見た目は控えめですが、完成品のどこにつながっているのかをたどると、工房を見る楽しみが増えると思います。',
 'お手元に革製品があれば、表側だけでなく、折れているところや部品が重なっているところも見てみてください。「平らな状態ではどんな形だったのかな」と想像するだけでも、身近な道具に知らなかった一面が見つかるかもしれません。分解したり、無理に広げたりする必要はありません。見える範囲で十分です。',
 '最後の写真には、今回の部品と対応する完成品を並べています。最初に想像した形と、同じでしたか？ 次は「革を切るところ」「部品を縫い合わせるところ」など、気になる工程があればコメントで教えてください。完成品だけでは見えない時間も、一緒に楽しんでいただけたら嬉しいです。'
 ]},
 {id:'light',parentId:null,group:'LEATHER',title:'光の向きで、革はどう見える？',message:'同じ革を同じ距離から、光の向きだけ変えて見比べる。',role:'新しい発見',object:'leather',preferred:'Reel',scenes:[['一枚の革を固定し、正面から撮る','同じ一枚の革です。まずは正面から。',false],['カメラの位置を固定し、光を斜めから当てる','光の向きを変えると、どこが違って見えますか？',false],['正面と斜めの写真を並べる','艶や凹凸の見え方を見比べてみてください。',false],['革をゆっくり傾けた短い動画','色だけでなく表情も。今日の投稿に比較を載せました。',false]],paragraphs:[
 '同じ一枚なのに、少し違う革に見える。そんな写真を見たことはありませんか？ 今日は一枚の革を使って、光の向きだけを変えて撮る企画です。別の色や別の素材へ取り替えず、同じ場所を見比べることを大切にしました。',
 '最初は正面から。次は少し斜めから光を当てます。明るく見えるところ、影になるところ、表面の細かな凹凸に注目してみてください。色の名前だけを読むと分からない部分にも、目が向くと思います。どちらが正しい写真かを決めるのではなく、ひとつの革が持ついくつかの見え方を知るための比較です。',
 'オンラインで選ぶときは、写真の印象が大切になりますよね。一枚目で気になった革も、近くで見たり、少し離れて見たりすると、好きなところが変わるかもしれません。逆に、画面だけでは決めきれないこともあると思います。そんなときに、別の角度を見たいと聞いていただくのも、選び方のひとつです。',
 '今回は、できるだけ比較する条件を揃えます。距離も背景も変えてしまうと、何による違いなのかが分かりにくくなるからです。撮る側が条件を一つずつ変えると、見ている方も「ここが変わった」と追いやすくなります。ただし、画面と実物の色を完全に一致させるという意味ではありません。',
 '革を選ぶとき、私たちも名前だけではなく、目の前にある表情を見ています。この投稿では難しい言葉で特徴を決めつけるより、まずご自身の目で違いを楽しんでいただきたいと思いました。お手元の革製品も、いつもの部屋と窓辺で印象が変わるか、無理のない範囲で眺めてみてください。',
 'つるっと見えるところが好きか、凹凸がはっきり見えるところが好きか。好みを言葉にできると、次に革を選ぶときの手がかりにもなります。どちらの見え方が気になりましたか？ 気づいた違いを、ひとつだけでも教えていただけたら嬉しいです。'
 ]},
 {id:'aging',parentId:null,group:'AGING',title:'変化を比べるなら、同じ場所から',message:'経年変化を断定せず、自分の革の変化を同じ条件の写真で残す。',role:'購入後',object:'none',preferred:'Carousel',scenes:[['日付メモと手持ちの革小物を撮る','今日の表情を、一枚残してみませんか。',false],['同じ背景・同じ角度で撮れる位置を示す','次も同じ場所から撮ると、見比べやすくなります。',false],['撮影日と使用期間を書くメモ','艶・色・形。どこを見比べたいですか？',false],['写真を保存する画面を撮る','変わったところも、変わらないところも、自分の記録に。',false]],paragraphs:[
 '毎日使っていると、少しずつの変化は意外と気づきにくいものです。久しぶりに前の写真を見て、「最初はこんな表情だったんだ」と感じることもありますよね。今日は、革を長く楽しむための写真の残し方を考えてみます。',
 '始めるときに必要なのは、きれいな撮影機材ではありません。いつものスマートフォンで、日付が分かる写真を一枚残すところからで十分です。次に撮るときも同じ向き、同じ背景にすると、どこを見比べているのかが分かりやすくなります。',
 '色だけを見ようとすると、部屋の明るさが変わっただけでも違って見えることがあります。そこで、全体の一枚に加えて、よく手が触れるところを少し近くで撮る方法もあります。何枚も撮り続けるのが負担なら、同じ一枚を残すだけでも大丈夫です。',
 '写真には、使い始めた時期や、どんな場面で持ち歩いているかを短く添えておくと、後から思い出しやすくなります。通勤で使う日が多かった、しばらく別の財布を使っていた、という日常のメモも、その人ならではの記録になります。',
 'ここで大切にしたいのは、「この期間で必ずこう変わる」と決めないことです。革や仕上げ、使い方が違えば、同じ見え方になるとは限りません。変化の大きさを競うのではなく、ご自身の持ち物をゆっくり知るための記録として楽しんでいただけたらと思います。',
 'もし気になる変化があったら、前の写真と今の写真があると、相談するときにも伝えやすくなります。写真だけで判断できないことはありますが、いつから気になったのかを一緒に教えていただけると、確認する手がかりになります。最初の一枚、今日のうちに残してみませんか。'
 ]},
 {id:'care',parentId:null,group:'CARE',title:'濡れた革の相談、何を伝える？',message:'素材が未確認のまま手入れ方法を断定せず、相談に必要な情報を揃える。',role:'購入後',object:'none',preferred:'Carousel',scenes:[['質問文を文字で表示する','革が濡れたら？ まず、どの革か確認したいです。',false],['商品名・カラーを記したメモ','購入時の商品名とカラーは分かりますか？',false],['全体写真と気になる部分の写真の撮り方','いつ、何で濡れたか。写真と一緒に教えてください。',false],['相談用メモを表示する','同じ方法で決めつけず、素材を確認してからお答えします。',false]],paragraphs:[
 '「革が濡れたときは、どうしたらいいですか？」。もしそんな場面があったら、まず何を伝えれば相談しやすいのか。今日は、お手入れ方法をひとつに決める前の、情報の揃え方をご紹介します。',
 'ひとくちに革といっても、素材や表面の仕上げはさまざまです。商品名が似ていても、使われている革が違うことがあります。そのため、素材を確認しないまま「どの革でもこの方法で大丈夫」とお伝えすることは避けたいと考えています。',
 '相談の際は、分かる範囲で商品名とカラーを教えてください。購入したときのページや注文内容に名前が残っていれば、それも手がかりになります。正式な名前が分からない場合は、全体の写真からでも構いません。分からないから相談できない、と思わなくて大丈夫です。',
 '次に、いつ、何で濡れたのか。気になったのは色なのか、触った感じなのか。それまでに何かお手入れをしたかも教えていただけると、状況を確認しやすくなります。長く説明しようとせず、分かることを短く並べていただければ十分です。',
 '写真は、製品の全体と、気になる部分の両方があると位置関係を追いやすくなります。ただ、画像だけでは質感などが分からない場合もあるので、写真だけで必ず判断できるというわけではありません。追加で確認したいことがあれば、こちらからお聞きします。',
 '大切な持ち物に変化があると、早く何とかしたくなりますよね。だからこそ、条件を確かめてから、その革に合わせて考えたいと思っています。この投稿は万能なお手入れ手順ではなく、困ったときに相談しやすくするためのメモです。商品名・写真・起きたこと。この三つを思い出せるよう、必要な方は保存しておいてください。'
 ]},
 {id:'choose',parentId:null,group:'CUSTOMER',title:'持ち歩きたいものから、財布を考える',message:'収納の多さだけでなく、自分の使い方と取り出し方で選ぶ。',role:'商品理解',object:'lineup',preferred:'Carousel',scenes:[['普段使うカード・現金を机に並べる','毎日使うものと、念のためのもの。分けてみませんか？',false],['カードと小銭の組み合わせを紙で示す','カードと小銭、どちらを多く持ち歩きますか？',false],['手持ちの物の量をメモする','量だけでなく、取り出す場面も思い浮かべてみてください。',false],['対象商品の開閉と手持ちを同じ順番で撮る','今日の投稿では、使う動きも一緒にご紹介します。',true]],paragraphs:[
 '財布を選ぶとき、「どれくらい入るか」は気になりますよね。でも、たくさん入れば自分に合うかというと、それだけでは決めにくいこともあります。今日は、いつも持ち歩くものと、使う場面から考えてみます。',
 'まずは、普段のお財布の中で、よく使うものを思い出してみてください。毎日使うカードと、たまに必要になるカード。現金で支払う場面と、スマートフォンで済む場面。人によって違うからこそ、「一般的にはこれだけ入れば十分」と決めずに考えたいところです。',
 'カードを少なくしたい方でも、小銭はある程度持ち歩きたいことがあります。反対に、現金はあまり使わなくても、仕事で必要なカードが多い方もいます。同じコンパクトな財布を探していても、気になる点はきっと違いますよね。',
 '今回の写真や動画では、見た目だけでなく、開いて取り出すまでの流れも見ていただきたいと思いました。手に持つ向き、置いて開く場面、閉じたときの様子。ご自身が使うところを想像しながら、気になるところを探してみてください。',
 '小ささを優先するか、余裕を持って収納するか。どちらかを正解にするのではなく、何を大切にしたいかが見つかると選びやすくなります。今の財布で気に入っているところと、少し変えたいところを一つずつ挙げてみるのもおすすめです。',
 '商品の仕様は確認できた内容をお伝えし、実際に入るか分からないものは、分からないままにしません。収納する物の大きさや量によって確認が必要なときは、具体的にお聞きしてからお答えします。普段の使い方を添えて相談していただけたら嬉しいです。'
 ]},
 {id:'sale',parentId:null,group:'PRODUCT',title:'次の販売で、自分に合うものを選ぶ',message:'登録した販売対象を比較し、選ぶ理由と販売日時を伝える。',role:'販売告知',object:'lineup',preferred:'Carousel',scenes:[['購入前に確認する三つのポイントを文字で示す','見た目・使う場面・気になること。購入前に整理してみましょう。',false],['色合わせを考える無地の紙と普段の小物','いつもの服や持ち物に、どんな色を合わせたいですか？',false],['質問欄を表示する','選ぶ前に確認したいことがあれば教えてください。',false],['販売対象を並べ、登録された販売日時を表示する','販売対象と日時は今日の投稿にまとめました。',true]],paragraphs:[
 '次のオンライン販売に向けて、今回ご紹介するアイテムをまとめました。気になっているものがある方も、まだ何となく眺めている方も、ご自身の毎日に合いそうかを考える時間になれば嬉しいです。',
 '写真を見て「この色が好き」と感じることは、選ぶときの大切なきっかけだと思います。その気持ちを大事にしながら、どこへ持っていくか、何と合わせるか、どんな場面で使うかも、少し想像してみてください。好きな見た目と使う姿がつながると、選ぶ理由もはっきりしてきます。',
 '同じアイテムの色違いを選ぶ日もあれば、今使っている財布に合わせて別の小物を選ぶ日もあると思います。ひとつずつ見るだけでなく、一緒に持ったときの組み合わせも楽しんでいただけるよう、今回は対象を並べてご紹介します。',
 '気になる商品が複数あるときは、まず使いたい場面をひとつ決めてみるのも方法です。普段のお出かけで使いたいのか、仕事で毎日使いたいのか。今の持ち物に加えたいのか、買い替えたいのか。比較する軸があると、見たい部分や聞きたいことも見つけやすくなります。',
 '作り手として、形や素材の良さをお伝えするだけでなく、納得して選んでいただくための情報も揃えたいと思っています。分からない部分は、雰囲気だけで想像して決めなくても大丈夫です。大きさや使い方など、購入前に確認したいことがあればご相談ください。',
 '販売は、私たちが次の製作を続けていくための大切な機会でもあります。気に入ってくださったものが、ご自身の暮らしの中で長く使いたいと思えるものになれば嬉しいです。気になる対象と販売日時を確認し、商品ページでも仕様をご覧ください。'
 ]},
 {id:'sound',parentId:null,group:'CRAFT',title:'工房の音を、少しだけ',message:'作業台の音と手元を楽しみ、ものづくりを身近に感じる。',role:'見る楽しさ',object:'none',preferred:'Reel',scenes:[['作業台に道具をそっと置く手元','今日は工房の音を少しだけ。',false],['紙を揃える手元を環境音付きで撮る','何の音か、想像してみてください。',false],['先ほどの手元を少し広く映す','答えは、紙を揃えている音でした。',false]],paragraphs:[
 '今日は少し趣向を変えて、工房の音をお届けします。画面を見られる方は手元と一緒に。音を出せる場所にいる方は、短い音にも耳を傾けてみてください。道具を置く、紙を揃える。そんな作業の合間にも、小さな違いがあります。',
 '完成した革製品の写真からは、工房でどんな音がしているのかまでは伝わりませんよね。今回は、大きな工程の説明ではなく、手を動かしている時間を少し身近に感じてもらえたらと思って撮る企画です。',
 '途中には、何をしている音か考える場面を入れました。最初は手元を近くから、そのあとに少し広く映します。音だけで分かった方も、映像を見て気づいた方もいると思います。答えを当てることより、普段は気に留めない音を楽しむ時間になれば嬉しいです。',
 'ものづくりを見る楽しさは、難しい技術を知ることだけではないと思っています。道具を置く位置や、手が動く順番、作業が切り替わる間。言葉で説明しなくても、画面から感じられることがあります。音を出せない場所でも分かるよう、何をしているかは短い文字で添えています。',
 'いつも見ている財布や小物にも、完成するまでには手を動かす時間があります。今日は商品を選ぶための比較ではありませんが、こうした時間を知ることで、使っているものへの親しみが少し増えたら嬉しいです。',
 '次に工房で見たいこと、聞いてみたい音はありますか？ 作業の流れが分かる動画と、こうした小さな場面の両方を、これからも少しずつお届けしていきたいと思います。'
 ]}
];
const BRIEF_PARENT_IDS={pattern:'official-64',light:'official-14',aging:'official-37',care:'official-43',choose:'official-92',sale:'official-92',sound:'official-64'};
for(const brief of BRIEFS){const parent=OFFICIAL_TOPICS.find(topic=>topic.id===BRIEF_PARENT_IDS[brief.id]);if(parent){brief.parentId=parent.id;brief.group=parent.group;}}
function generatedConceptError(post){const parent=OFFICIAL_TOPICS.find(topic=>topic.id===post?.parentId);if(!parent)return '正式100テーマの親テーマがありません。';if(!Object.hasOwn(AXES,post.primaryAxis))return '主目的が正式3軸に含まれていません。';if(post.topicGroup!==parent.group)return '親テーマと分類が一致していません。';if(parent.researchRequired&&post.researchRequired!==true)return 'INDUSTRY 66〜80は要リサーチです。';return '';}
function topicLabel(p){const t=OFFICIAL_TOPICS.find(t=>t.id===p.parentId);return t?`${t.group} #${String(t.number).padStart(2,'0')}｜${t.title||'原文未確認'}`:`${p.topicGroup||'未分類'}｜追加テーマ案（正式100とは別）`;}
function salesContext(date){const all=Object.values(demo.months).filter(m=>m.date).sort((a,b)=>a.date.localeCompare(b.date));const next=all.find(m=>m.date>=date),previous=all.filter(m=>m.date<date).at(-1);return {next,previous,until:next?dayDiff(next.date,date):null,after:previous?dayDiff(date,previous.date):null};}
function voiceText(r){return [r.question,...r.answers,...r.dm,r.theme].join(' ');}
function voiceCandidates(){return demo.reactions.map(r=>({id:r.id,question:r.question,route:r.route||(/要望|欲しい|小銭.*多|カード.*少/.test(voiceText(r))?'商品開発候補':'情報発信'),brief:/濡|雨|手入|修理/.test(voiceText(r))?'care':/収納|小銭|カード|サイズ/.test(voiceText(r))?'choose':null,confirmed:!!r.route}));}
function captureBand(t,r){if(!r||r.missed)return '未取得';const at=new Date(r.observedAt+'+09:00').getTime();return at<t.start?'早期取得':at>t.end?'遅延取得':'期間内';}
function resultSummary(p){const tasks=allTasks().filter(t=>t.p.id===p.id),entry=stage=>{const t=tasks.find(t=>t.stage===stage),record=t&&demo.records[t.key];if(!record)return null;const band=record.captureBand||captureBand(t,record);return {stage,band,record};},seven=entry('7d'),day=entry('24h');return {postId:p.id,sevenDay:seven?.band==='期間内'?seven.record:null,provisional24h:!seven?.record&&day?.band==='期間内'?day.record:null,delayed:[seven,day].filter(x=>x?.band==='遅延取得').map(x=>({stage:x.stage,record:x.record}))};}
function planContext(date){const c=salesContext(date),all=demo.posts.filter(p=>!p.deleted&&!p.paused&&p.date<date).sort((a,b)=>a.date.localeCompare(b.date)),base=all.slice(-10),baseResults=base.filter(p=>p.actualAt).map(resultSummary),extend=(c.until!==null&&c.until<=14)||c.next?.lineup.some(l=>l.saleKind==='新発売')||baseResults.filter(r=>r.sevenDay).length<3,limit=extend?20:10,recent=all.slice(-limit),month=demo.posts.filter(p=>!p.deleted&&!p.paused&&p.date.slice(0,7)===date.slice(0,7));return {...c,recent,recentLimit:limit,resultPosts:recent.filter(p=>p.actualAt).map(resultSummary),month,voices:voiceCandidates().filter(v=>v.brief),events:demo.events.filter(e=>e.start<=date&&e.end>=date)};}
function chooseAxis(c){if(c.until!==null&&c.until<=3)return 'BUSINESS';if(c.after!==null&&c.after<=3)return 'CUSTOMER_VALUE';const score={CUSTOMER_VALUE:1,INSTAGRAM_GROWTH:1,BUSINESS:1};if(c.until!==null&&c.until<=14)score.BUSINESS+=2;if(c.voices.length)score.CUSTOMER_VALUE+=.8;if(c.next?.lineup.some(l=>l.saleKind==='新発売'))score.BUSINESS+=1;if(c.events.length)score.BUSINESS+=1;for(const p of c.recent)if(p.primaryAxis)score[p.primaryAxis]-=.45;for(const axis of Object.keys(score))if(!c.month.some(p=>p.primaryAxis===axis))score[axis]+=.6;const last=c.recent.at(-1);if(last?.primaryAxis)score[last.primaryAxis]-=1;return Object.keys(score).sort((a,b)=>score[b]-score[a])[0];}
function chooseBrief(axis,c){const pool=BRIEFS;return pool.map(b=>{let score=1;if(axis==='BUSINESS'&&['販売告知','商品理解'].includes(b.role))score+=2;if(axis==='INSTAGRAM_GROWTH'&&['見る楽しさ','新しい発見'].includes(b.role))score+=2;if(axis==='CUSTOMER_VALUE'&&['購入後','製作背景','新しい発見'].includes(b.role))score+=2;const used=c.recent.filter(p=>p.briefId===b.id).length;score-=used*2.5;if(c.recent.at(-1)?.topicGroup===b.group)score-=1.5;if(c.voices.some(v=>v.brief===b.id&&['情報発信','両方'].includes(v.route)))score+=1.2;if(c.after!==null&&c.after<=7&&b.role==='購入後')score+=2;if(c.until!==null&&c.until<=3&&b.id==='sale')score+=4;if(!demo.posts.some(p=>p.briefId===b.id))score+=1;return {b,score};}).sort((a,b)=>b.score-a.score)[0].b;}
function selectSubjects(b,c){if(b.object==='none'||b.object==='leather')return [];let candidates=b.object==='mini'?demo.skus.filter(s=>!s.deleted&&item(s.itemId)?.name==='mini wallet'):(c.next?.lineup||c.previous?.lineup||[]).map(l=>sku(l.skuId)).filter(s=>s&&!s.deleted);if(!candidates.length)return [];const prev=c.recent.at(-1);const previousItems=(prev?.skuIds||[]).map(id=>sku(id)?.itemId);candidates.sort((a,z)=>{const score=s=>(c.next?.lineup.find(l=>l.skuId===s.id)?.priority?4:0)-(previousItems.includes(s.itemId)?3:0)-((prev?.skuIds||[]).includes(s.id)?5:0)-(/black|noir|nero/.test(s.name)&&prev?.skuIds.some(id=>/black|noir|nero/.test(sku(id)?.name||''))?2:0);return score(z)-score(a);});const selected=[candidates[0]];if(b.object==='lineup'){const second=candidates.find(s=>s.itemId!==selected[0].itemId)||candidates[1];if(second)selected.push(second);const third=candidates.find(s=>!selected.includes(s)&&!selected.some(a=>a.name===s.name));if(third)selected.push(third);}return selected.map(s=>s.id);}
function formatEvidence(axis,group){return ['Reel','Feed'].map(format=>{const ps=demo.posts.filter(p=>{const a=actualPost(p);return p.actualAt&&a?.primaryAxis===axis&&a.topicGroup===group&&a.format===format&&!a.advertised&&!demo.ads.some(ad=>ad.postId===p.id)&&primaryRecord(p)});const rates=ps.map(p=>primaryRecord(p)).filter(r=>r.views>0&&typeof r.saves==='number').map(r=>r.saves/r.views);const outcome=ps.map(p=>primaryRecord(p)).filter(r=>r.views>0&&typeof (axis==='INSTAGRAM_GROWTH'?r.follows:r.saves)==='number').map(r=>(axis==='INSTAGRAM_GROWTH'?r.follows:r.saves)/r.views);return {format,count:ps.length,savePerView:rates.length?rates.reduce((a,b)=>a+b,0)/rates.length:null,outcomeRate:axis==='BUSINESS'?null:outcome.length?outcome.reduce((a,b)=>a+b,0)/outcome.length:null,comparisonNote:'仮案：両形式3件以上の同主目的・分類・広告なし7dを参考。価値は保存/再生、届ける力はフォロー/再生。BUSINESSは声の文脈を分析で確認。因果関係や売上を断定しない。'};});}
function createConcept(date,index=0,forced){const c=planContext(date),axis=forced==='pattern'?'CUSTOMER_VALUE':chooseAxis(c),b=forced?BRIEFS.find(b=>b.id===forced):chooseBrief(axis,c),ids=selectSubjects(b,c),evidence=formatEvidence(axis,b.group);let format=b.preferred==='Carousel'?'Feed':b.preferred;const last=c.recent.slice(-2);if(last.length===2&&last.every(p=>p.format===format))format=format==='Reel'?'Feed':'Reel';const comparable=evidence.filter(e=>e.count>=3&&e.outcomeRate!==null);if(comparable.length===2&&Math.abs(comparable[0].outcomeRate-comparable[1].outcomeRate)>.001){const learned=comparable.slice().sort((a,b)=>b.outcomeRate-a.outcomeRate)[0].format;if(!last.every(p=>p.format===learned))format=learned;}const reason=c.until!==null&&c.until<=3?'販売直前：対象商品を起点に、選ぶ理由と販売日時を伝える。':c.after!==null&&c.after<=3?'販売後：購入後の楽しみと使う場面を増やす。':'販売予定、直近の主目的・テーマ、質問と新しい探索を合わせて選定。';const p={id:newId(),date,plannedTime:'18:00',actualAt:null,skuIds:ids,theme:b.title,primaryAxis:axis,parentId:b.parentId,topicGroup:b.group,briefId:b.id,themeId:b.id,derivedTheme:b.title,takeaway:b.message,role:b.role,subjects:b.object==='leather'?'撮影する一枚の革（素材名を確認）':b.object==='none'?'工房・記録用の写真と道具':ids.map(skuLabel).join(' ＋ '),format,purpose:axisShort[axis],planningReason:reason,formatReason:`${b.preferred==='Reel'?'工程・動き':'順番に読み返す内容'}を基準に提案。同じ主目的・分類・広告なしの7d記録：リール${evidence[0].count}件、Feed${evidence[1].count}件。形式の優劣は未断定。仮案として、同条件で各形式3件以上あれば目的に対応する反応率も参考にします。`,voiceIds:c.voices.filter(v=>v.brief===b.id&&['情報発信','両方'].includes(v.route)).map(v=>v.id),caption:b.paragraphs.join('\n\n'),hook:b.scenes[0][1],cta:b.scenes.at(-1)[1],stories:[],shots:[],sequence:[],revision:1,manual:false,paused:blocked(date),conceptVersion:2,researchRequired:false,reviewNeeded:[]};
 const parent=OFFICIAL_TOPICS.find(topic=>topic.id===p.parentId);p.topicGroup=parent?.group||p.topicGroup;p.researchRequired=!!parent?.researchRequired;
 if(b.id==='sale'){p.caption+='\n\n今回の対象：\n'+(ids.length?ids.map(skuLabel).join('\n'):'販売対象は未登録です。')+'\n\n販売日時：'+(c.next?c.next.date+' '+c.next.time:'未登録（掲載前に確認）');if(!ids.length)p.reviewNeeded.push('販売対象の登録が必要');}
 if(b.id==='choose'&&ids.length)p.caption+='\n\n今回ご紹介する対象：\n'+ids.map(skuLabel).join('\n')+'\n\n仕様は商品カルテと実物で確認しながらご案内します。';
 p.sequence=b.scenes.map(([asset,text,product],i)=>({order:i+1,visual:asset,words:text,shotId:p.id+'-shot-'+i}));
 p.shots=b.scenes.map(([asset,text,product],i)=>({id:p.id+'-shot-'+i,signature:[b.id,i,format,product?ids.join('|'):''].join('|'),media:format==='Reel'?'動画':'写真',what:asset,skuIds:product?[...ids]:[],count:1}));
 p.stories=b.scenes.map(([asset,text,product],i)=>({text,asset:(p.shots[i].media==='動画'?'動画：':'写真：')+asset,purpose:i===1&&b.id==='pattern'?'クイズ':product?'投稿・商品理解':'見る楽しみ',action:i===1&&b.id==='pattern'?'答えを考えて回答する':product?'今日の投稿を開く':'次の場面を見る',skuIds:product?[...ids]:[],participatory:(i===1&&b.id==='pattern')||(i===2&&b.id==='sale'),shotId:p.shots[i].id}));
 const invalid=generatedConceptError(p);if(invalid)throw Error('投稿案を追加できません：'+invalid);return p;}
const briefConcept=createConcept;
formatEvidence=function(axis,group,date=demo.planStart||TODAY){const context=planContext(date),results=new Map(context.resultPosts.filter(x=>x.sevenDay).map(x=>[x.postId,x.sevenDay]));return ['Reel','Feed'].map(format=>{const ps=demo.posts.filter(p=>{const a=actualPost(p);return results.has(p.id)&&a?.primaryAxis===axis&&a.topicGroup===group&&a.format===format&&!a.advertised&&!demo.ads.some(ad=>ad.postId===p.id)}),records=ps.map(p=>results.get(p.id)),rates=records.filter(r=>r.views>0&&typeof r.saves==='number').map(r=>r.saves/r.views),outcome=records.filter(r=>r.views>0&&typeof (axis==='INSTAGRAM_GROWTH'?r.follows:r.saves)==='number').map(r=>(axis==='INSTAGRAM_GROWTH'?r.follows:r.saves)/r.views);return {format,count:ps.length,savePerView:rates.length?rates.reduce((a,b)=>a+b,0)/rates.length:null,outcomeRate:axis==='BUSINESS'?null:outcome.length?outcome.reduce((a,b)=>a+b,0)/outcome.length:null,comparisonNote:`直近${context.recentLimit}投稿を上限に、期間内7dを優先。24hは暫定、遅延取得は参考として分離。`};});};
const TOPIC_AXIS_GROUPS={CUSTOMER_VALUE:['LEATHER','AGING','CARE','CRAFT','CUSTOMER','ANIMAL'],INSTAGRAM_GROWTH:['LEATHER','ANIMAL','CRAFT','FASHION','INDUSTRY'],BUSINESS:['CUSTOMER','FASHION','CARE','AGING','CRAFT']};
const TOPIC_ANGLES={LEATHER:['見え方を比べる','選ぶ前に確かめる','身近な革で見つける'],ANIMAL:['違いを見比べる','使う場面から考える','特徴を確かめる'],AGING:['今の表情を残す','変化を見比べる','長く楽しむ'],CARE:['困ったときに確かめる','長く使うために知る','実物に合わせて考える'],CRAFT:['手元から知る','工程をたどる','道具と仕立てを見る'],INDUSTRY:['最新資料から確認する','事実と背景を調べる','出典を確かめる'],FASHION:['暮らしに合わせて考える','装いとの組み合わせを見る','今の使い方を考える'],CUSTOMER:['使う場面から選ぶ','購入前の疑問を確かめる','使った後まで考える']};
const CTA_BY_AXIS={CUSTOMER_VALUE:['あとで見返せるよう保存してください。','気になったことを質問で教えてください。','お手元で気づいたことがあれば教えてください。'],INSTAGRAM_GROWTH:['知らなかった方へシェアしてください。','次に見たい内容をコメントで教えてください。','革の発見を続けて見たい方はフォローしてください。'],BUSINESS:['気になる仕様は購入前にご質問ください。','販売予定と対象商品をご確認ください。','使う場面に合う商品を見比べてください。']};
function blockStartFor(date){const start=demo.planStart||date;return date>=start&&date<=dayAdd(start,9)?start:date;}
function topicCandidates(axis,c,date,attempt=0){const start=blockStartFor(date),block=demo.posts.filter(p=>!p.deleted&&p.date>=start&&p.date<=dayAdd(start,9)),recent=c.recent,last=recent.at(-1);return OFFICIAL_TOPICS.map(topic=>{let score=(TOPIC_AXIS_GROUPS[axis]||[]).includes(topic.group)?6:1;if(block.some(p=>p.parentId===topic.id))score-=30;if(recent.some(p=>p.parentId===topic.id))score-=12;if(last?.parentId===topic.id)score-=20;if(last?.topicGroup===topic.group)score-=2;if(c.until!==null&&c.until<=3&&topic.group==='CUSTOMER')score+=8;if(c.until!==null&&c.until<=7&&['CUSTOMER','FASHION'].includes(topic.group))score+=3;if(c.after!==null&&c.after<=5&&['AGING','CARE','CUSTOMER'].includes(topic.group))score+=3;if(c.next?.lineup.some(l=>l.priority)&&['CUSTOMER','FASHION','CARE'].includes(topic.group))score+=2;if(topic.researchRequired)score-=1;score+=((topic.number+Math.abs(dayDiff(date,'2026-01-01'))+attempt*17)%101)/1000;return {topic,score};}).sort((a,b)=>b.score-a.score||a.topic.number-b.topic.number).map(x=>x.topic);}
function conceptSubjects(template,c,attempt){const first=selectSubjects(template,c);if(attempt===0||template.object!=='lineup')return first;const pool=(c.next?.lineup||c.previous?.lineup||[]).map(l=>sku(l.skuId)).filter(s=>s&&!s.deleted);if(!pool.length)return first;const ordered=pool.slice().sort((a,b)=>{const priority=s=>c.next?.lineup.find(l=>l.skuId===s.id)?.priority?1:0;return priority(b)-priority(a)||a.id.localeCompare(b.id);}),offset=attempt%ordered.length;return [...ordered.slice(offset),...ordered.slice(0,offset)].slice(0,Math.min(3,ordered.length)).map(s=>s.id);}
function safeConceptCta(axis,ids,variant=0,date=TODAY){const products=ids.map(sku).filter(Boolean),statuses=new Set(products.map(s=>s.status)),pick=xs=>xs[variant%xs.length],sale=salesContext(date),upcoming=(sale.next?.lineup||[]).filter(l=>ids.includes(l.skuId)),kinds=new Set(upcoming.map(l=>l.saleKind));if(upcoming.length&&sale.until!==null&&sale.until>=0){if(kinds.has('新発売'))return pick(['販売予定を確認し、気になる点は事前にご質問ください。','発売予定と商品の仕様をご確認ください。']);if(kinds.has('再販'))return pick(['再販予定を確認し、気になる点は事前にご質問ください。','次回の再販案内を確認できるよう、お知らせをご覧ください。']);if(kinds.size===1&&kinds.has('常時販売')&&statuses.size===1&&statuses.has('selling'))return pick(['商品ページで現在の仕様をご確認ください。','使う場面に合うか商品ページで見比べてください。']);}if(statuses.has('soldout'))return statuses.has('selling')?pick(['販売状況を商品ごとに確認し、気になる点は事前にご質問ください。','商品ごとの在庫・次回予定をご確認ください。']):pick(['次回販売予定を確認したい方はお知らせをご覧ください。','今後の販売について知りたい点があれば事前にご質問ください。']);if(statuses.has('restock'))return pick(['販売再開の予定を確認し、気になる点は事前にご質問ください。','次回の販売案内を確認できるよう、お知らせをご覧ください。']);if(statuses.has('selling'))return axis==='BUSINESS'?pick(['販売中の商品ページで仕様をご確認ください。','使う場面に合うか商品ページで見比べてください。']):CTA_BY_AXIS[axis][variant%CTA_BY_AXIS[axis].length];return CTA_BY_AXIS[axis][variant%CTA_BY_AXIS[axis].length];}
function topicTemplate(topic,axis,index,attempt){const base=BRIEFS.find(b=>b.group===topic.group)||BRIEFS.find(b=>axis==='BUSINESS'&&b.id==='choose')||BRIEFS[(topic.number+index+attempt)%BRIEFS.length],angle=TOPIC_ANGLES[topic.group][(index+attempt)%TOPIC_ANGLES[topic.group].length],object=axis==='BUSINESS'||topic.group==='CUSTOMER'?'lineup':topic.group==='LEATHER'?'leather':'none';return {...base,id:'topic-'+String(topic.number).padStart(2,'0')+'-'+angle,parentId:topic.id,group:topic.group,title:topic.title+'｜'+angle,message:'正式テーマ「'+topic.title+'」を、'+angle+'視点で分かりやすく伝える。',role:angle,object,preferred:(topic.number+index)%3===0?'Carousel':'Reel',paragraphs:[topic.researchRequired?'このテーマは最新資料と出典の確認後に本文を仕上げます。':'今回は「'+topic.title+'」を、'+angle+'視点で見ていきます。実物と登録情報を確認し、断定しすぎずにお伝えします。','気になった点や次に詳しく見たいところがあれば教えてください。'],scenes:[['親テーマに合う実物・工程・資料を確認する',topic.title,false],['違いが分かる場面を同じ条件で見せる',angle,false],['要点を一つに絞って伝える','今日分かったことを振り返ります。',object==='lineup']]};}
function normalizeTheme(text){return String(text||'').normalize('NFKC').toLowerCase().replace(/[\s　・｜「」『』、。？！?!]/g,'');}
function themeWords(text){const s=normalizeTheme(text);return new Set(Array.from({length:Math.max(0,s.length-1)},(_,i)=>s.slice(i,i+2)));}
function nearTheme(a,b){const na=normalizeTheme(a),nb=normalizeTheme(b);if(!na||!nb)return false;if(na===nb)return true;const wa=themeWords(na),wb=themeWords(nb),same=[...wa].filter(x=>wb.has(x)).length;return same/Math.max(1,Math.min(wa.size,wb.size))>=.72;}
function completeGeneratedCaption(post){if([...String(post.caption||'')].length>=300)return;const products=post.skuIds.length?post.skuIds.map(skuLabel).join('、'):'今回撮影する革や道具';const focus={LEATHER:'表面の模様だけでなく、厚みや柔らかさ、光を受けたときの表情まで見比べると、革ごとの個性が分かりやすくなります。',ANIMAL:'動物の種類だけで決めつけず、部位・なめし・仕上げまで確認することが、革を正しく知る手がかりになります。',AGING:'変化の速さや現れ方は、使う頻度、触れ方、保管環境でも異なります。誰かと同じ色にするのではなく、自分の時間として楽しんでください。',CARE:'まず素材と仕上げを確認し、目立たない場所で少量から試すことが大切です。迷う場合は、自己判断で進めず写真と商品名を添えてご相談ください。',CRAFT:'完成品だけでなく、型紙・裁断・縫製・仕上げのどこで形や使い心地が決まるのかを、手元の動きと一緒にお伝えします。',INDUSTRY:'未確認の情報は断定せず、出典と確認日を確かめたうえで、暮らしや革選びにどう関係するかを整理します。',FASHION:'流行だけを追うのではなく、いつもの服や持ち物に合わせたときの色・大きさ・素材の見え方を考えます。',CUSTOMER:'いただいた質問や使う場面を出発点に、選ぶ前の迷いと使い始めてからの困りごとを一つずつ整理します。'}[post.topicGroup]||'実物を見ながら、暮らしの中で役立つポイントを具体的に確かめます。';post.caption=[post.caption,`今回見るのは「${post.theme}」です。${focus}`,`${products}を例に、見た目だけでは分かりにくい部分も写真や工程で確かめます。使う場面を思い浮かべながら、今持っているものとの違い、手に取るときに確認したい点、長く使うために知っておきたいことを順番にご紹介します。`,`作り手として、形や素材を選んだ理由だけでなく、できることと注意したいことも同じように伝えたいと考えています。気になる点や、ご自身の使い方で迷っていることがあれば、コメントやDMで教えてください。次の投稿やご案内を、実際のお声に沿って分かりやすくする参考にします。`,post.cta].filter(Boolean).join('\n\n');}
createConcept=function(date,index=0,forced,attempt=0){if(forced)return briefConcept(date,index,forced);const c=planContext(date),preferred=chooseAxis(c),axes=[preferred,...Object.keys(AXES).filter(axis=>axis!==preferred)],axis=axes[attempt%axes.length],topic=topicCandidates(axis,c,date,attempt)[attempt%12],template=topicTemplate(topic,axis,index,attempt);BRIEFS.push(template);let post;try{post=briefConcept(date,index,template.id);}finally{BRIEFS.pop();}post.briefId=template.id;post.themeId=template.id;post.primaryAxis=axis;post.parentId=topic.id;post.topicGroup=topic.group;post.derivedTheme=template.title;post.theme=template.title;post.takeaway=template.message;post.researchRequired=!!topic.researchRequired;post.skuIds=conceptSubjects(template,c,attempt);post.subjects=post.skuIds.length?post.skuIds.map(skuLabel).join(' ＋ '):post.subjects;post.cta=safeConceptCta(axis,post.skuIds,index+attempt,date);post.planningReason+=' 正式100テーマから未使用・直近重複・販売状況を確認して選定。';completeGeneratedCaption(post);const invalid=generatedConceptError(post);if(invalid)throw Error('投稿案を追加できません：'+invalid);return post;};
function planConflict(post,previous,block){const sale=salesContext(post.date),nearSale=sale.until!==null&&sale.until<=3,priorityIds=post.skuIds.filter(id=>sale.next?.lineup.some(l=>l.skuId===id&&l.priority)),priority=priorityIds.length>0,blockSale=salesContext(blockStartFor(post.date)),eventReason=demo.events.some(e=>e.start<=post.date&&e.end>=post.date),categoryException=nearSale||eventReason;if(block.some(p=>p.parentId===post.parentId)&&!nearSale)return 'parent';if(block.some(p=>nearTheme(p.derivedTheme||p.theme,post.derivedTheme||post.theme)))return 'theme';if(block.filter(p=>p.topicGroup===post.topicGroup).length>=3&&!categoryException)return 'category';const priorityLimit=blockSale.until!==null&&blockSale.until<=3?5:blockSale.until!==null&&blockSale.until<=7&&priorityIds.some(id=>sale.next?.lineup.find(l=>l.skuId===id)?.saleKind==='新発売')?4:3;if(priorityIds.some(id=>block.filter(p=>p.skuIds.includes(id)).length>=priorityLimit))return 'priority';if(previous){const sameSku=post.skuIds.some(id=>previous.skuIds.includes(id)),sameItem=post.skuIds.some(id=>previous.skuIds.some(x=>sku(x)?.itemId===sku(id)?.itemId)),sameColor=post.skuIds.some(id=>previous.skuIds.some(x=>sku(x)?.name&&sku(x)?.name===sku(id)?.name)),sameMaterial=post.skuIds.some(id=>previous.skuIds.some(x=>sku(x)?.material&&sku(x)?.material===sku(id)?.material)),black=post.skuIds.some(id=>/black|noir|nero/i.test(sku(id)?.name||''))&&previous.skuIds.some(id=>/black|noir|nero/i.test(sku(id)?.name||''));if(sameSku||black||((sameItem||sameColor||sameMaterial)&&!priority))return 'product';if(previous.topicGroup===post.topicGroup&&block.at(-2)?.topicGroup===post.topicGroup&&!categoryException)return 'category-sequence';if(previous.format===post.format&&block.at(-2)?.format===post.format)return 'format';if(previous.primaryAxis===post.primaryAxis&&block.at(-2)?.primaryAxis===post.primaryAxis&&!nearSale)return 'axis';if(normalizeTheme(previous.cta)===normalizeTheme(post.cta))return 'cta';if(previous.briefId===post.briefId||previous.role===post.role)return 'brief';}return '';}
function generatePlanDates(dates){const created=[];for(let i=0;i<dates.length;i++){const date=dates[i];if(demo.posts.some(p=>p.date===date&&!p.deleted)||blocked(date))continue;const block=demo.posts.filter(p=>!p.deleted&&dates.includes(p.date)&&p.date<date).sort((a,b)=>a.date.localeCompare(b.date));let post,attempt=0;do{post=createConcept(date,i,null,attempt++);}while(planConflict(post,block.at(-1),block)&&attempt<25);if(planConflict(post,block.at(-1),block))throw Error(short(date)+'の重複を解消できませんでした。');demo.posts.push(post);created.push(post);}return created;}
function actualPost(p){return p.actualSnapshot?{...p,...p.actualSnapshot,id:p.id,date:jstDate(p.actualAt),actualAt:p.actualAt}:null;}
function migrateConcepts(){demo.topicRegistry=OFFICIAL_TOPICS;demo.extraThemes||=[];for(const b of BRIEFS)if(!demo.extraThemes.some(t=>t.id===b.id))demo.extraThemes.push({id:b.id,parentId:b.parentId,title:b.title,group:b.group,status:b.parentId?'派生テーマ':'追加テーマ案',source:'今回の仮データ用企画',uses:[]});const before=demo.posts.length;demo.posts=demo.posts.filter(p=>!blocked(p.date)||p.manual||p.actualAt);const cleaned=demo.posts.length!==before;if(demo.conceptVersion===2){if(cleaned)persist();return;}for(const p of demo.posts){if(p.manual||p.actualAt){p.actualContentVerified=!!p.actualSnapshot;p.conceptVersion||=1;continue;}const fresh=createConcept(p.date,0,p.date===TODAY?'pattern':null);Object.assign(p,fresh,{id:p.id,revision:p.revision+1});}demo.conceptVersion=2;persist();}
const feedReelConcept=createConcept;
createConcept=function(...args){const post=feedReelConcept(...args);if(post.format==='Carousel'){post.format='Feed';for(const shot of post.shots||[])shot.signature=String(shot.signature||'').replace('|Carousel|','|Feed|');}return post;};
const previousDraft=draftPost;draftPost=(date,index)=>createConcept(date,index);
proposeMissing=function(){try{const to=salesCycleBlock(demo.planStart)?.to||dayAdd(demo.planStart,9),created=generatePlanDates(Array.from({length:dayDiff(to,demo.planStart)+1},(_,i)=>dayAdd(demo.planStart,i)));persist();refreshWork();toast(created.length+'日分の未作成案を追加しました。編集済み投稿は保持しました。');}catch(e){toast(e.message);}};
const oldShowPost=showPost;
showPost=function(id){oldShowPost(id);const p=demo.posts.find(p=>p.id===id);const details=dax('#dayDetail > details').find(d=>d.querySelector('summary')?.textContent.startsWith('Story '));if(details){const section=document.createElement('section');section.className='stories-always';section.innerHTML='<h3>Story '+p.stories.length+'案</h3>'+[...details.children].filter(e=>e.tagName!=='SUMMARY').map(e=>e.outerHTML).join('');details.replaceWith(section);}dx('#dayDetail').insertAdjacentHTML('afterbegin',`<p class="tiny muted">${html(topicLabel(p))}</p>${p.takeaway?`<p class="takeaway">${html(p.takeaway)}</p>`:''}${p.researchRequired?'<p class="notice">要リサーチ：確認前の事実・数値は投稿しません。</p>':''}${p.manual&&p.conceptVersion!==2&&!p.actualAt?'<p class="notice">編集済みの内容を保持しています。主目的・企画のつながりは確認が必要です。</p>':''}<details class="concept-detail"><summary>企画の意図・構成</summary><p>${html(AXES[p.primaryAxis]||'主目的は未確認')}</p><p>${html(p.planningReason||'旧版の企画。自動で再生成していません。')}</p><p>${html(p.formatReason||'')}</p>${(p.sequence||[]).map((s,i)=>`<p><strong>${p.format==='Reel'?i===0?'0〜3秒':(3+(i-1)*5)+'〜'+(8+(i-1)*5)+'秒':(i+1)+'枚目'}</strong><br>${html(s.visual)}<br>載せる言葉：${html(s.words)}</p>`).join('')}<button class="ghost full" data-concept-edit="${p.id}">主目的・伝えること・構成を編集</button></details>`);};
const actualConfirmationDetail=showPost;showPost=function(id){actualConfirmationDetail(id);const p=demo.posts.find(post=>post.id===id),button=dx('#dayDetail [data-work-publish]');if(!p?.actualAt||!button)return;if(p.actualSnapshot){button.insertAdjacentHTML('beforebegin','<p class="tiny muted">実際の投稿内容は確認済みです。</p>');return;}button.textContent='内容を変更して投稿した';button.insertAdjacentHTML('beforebegin',`<p class="tiny muted">投稿日時は登録済み・実際の内容は未確認です。予定どおりなら一度だけ確認してください。</p><button class="secondary" data-work-confirm-planned="${p.id}">予定どおり投稿した</button>`);};
document.addEventListener('click',e=>{const button=e.target.closest('[data-work-confirm-planned]');if(!button)return;e.stopImmediatePropagation();const p=demo.posts.find(post=>post.id===button.dataset.workConfirmPlanned);if(!p?.actualAt||p.actualSnapshot)return;try{p.actualSnapshot=reviewActualChoice(p,{get:key=>key==='reviewActualChoice'?'planned':null,getAll:()=>[]});p.actualContentVerified=true;p.revision++;persist();refreshWork();showPost(p.id);}catch(err){toast(err.message);}},true);
function editConcept(id){const p=demo.posts.find(p=>p.id===id);dx('#dayDialog').close();openForm('企画の意図',formSelect('主目的','primaryAxis',[['','未確認'],...Object.entries(AXES)],p.primaryAxis||'')+formSelect('親テーマ','parentId',[['','追加テーマ・親テーマ未指定'],...OFFICIAL_TOPICS.filter(t=>t.verified).map(t=>[t.id,t.group+' #'+t.number+' '+t.title])],p.parentId||'')+formInput('分類','topicGroup',p.topicGroup||'')+formInput('派生テーマ','derivedTheme',p.derivedTheme||p.theme)+formInput('今日伝えること','takeaway',p.takeaway||'')+formInput('使う革・素材・工程・道具','subjects',p.subjects||'')+`<label class="wlabel">構成（1行＝1場面。「画面｜載せる言葉」）<textarea name="sequence" rows="5">${html((p.sequence||[]).map(s=>s.visual+'｜'+s.words).join('\n'))}</textarea></label><p class="tiny muted">本文・Storyは勝手に変更しません。テーマを変えたときは内容のつながりも確認してください。</p>`,f=>{p.primaryAxis=f.get('primaryAxis')||null;p.parentId=f.get('parentId')||null;p.topicGroup=p.parentId?OFFICIAL_TOPICS.find(t=>t.id===p.parentId).group:f.get('topicGroup');p.derivedTheme=f.get('derivedTheme');p.theme=p.derivedTheme;p.takeaway=f.get('takeaway');p.subjects=f.get('subjects');p.sequence=String(f.get('sequence')).split('\n').filter(Boolean).map((line,i)=>{const [visual,...words]=line.split('｜');return {order:i+1,visual,words:words.join('｜'),shotId:p.shots[i]?.id||null};});p.researchRequired=p.topicGroup==='INDUSTRY';p.manual=true;p.revision++;});}
function axisBalance(posts){const ps=posts.filter(p=>!p.paused&&!p.deleted);return {counts:Object.fromEntries(Object.keys(AXES).map(a=>[a,ps.filter(p=>p.primaryAxis===a).length])),unknown:ps.filter(p=>!p.primaryAxis).length,notes:[...(!ps.some(p=>p.primaryAxis==='BUSINESS')?['商品理解・販売につなげる企画を確認']:[]),...(!ps.some(p=>p.primaryAxis==='INSTAGRAM_GROWTH')?['新しい人が見るきっかけを確認']:[]),...(!ps.some(p=>p.role==='購入後')?['購入後の使い方・楽しみも候補に']:[]),...(ps.some((p,i)=>i>0&&p.topicGroup&&p.topicGroup===ps[i-1].topicGroup)?['同じ分類が続く箇所を確認']:[])]};}
function balanceHTML(posts){const b=axisBalance(posts);return `<div class="axis-counts">${Object.keys(AXES).map(a=>`<div><strong>${b.counts[a]}</strong><small>${html(axisShort[a])}</small></div>`).join('')}</div><p class="tiny muted">固定比率なし${b.unknown?' · 主目的未確認 '+b.unknown+'件':''}</p>${b.notes.map(n=>`<p class="tiny">${n}</p>`).join('')}`;}
const oldRenderPlan=renderPlan;
renderPlan=function(){oldRenderPlan();dx('#planList').innerHTML=rangePosts().map(p=>`<article class="card"><div class="row between"><span class="badge">${planDay(p.date)}</span><span class="badge">${formats[p.format]}</span></div><p class="tiny muted">${html(topicLabel(p))}</p><h3>${html(p.derivedTheme||p.theme)}</h3><p>${html(p.takeaway||'伝えることは未確認')}</p><p class="exact muted">${html(p.skuIds.length?postLabel(p):p.subjects||'革・工程・道具')}</p><div class="row"><span class="badge">${html(axisShort[p.primaryAxis]||'主目的未確認')}</span><span class="tiny">${p.stories.length} Story · ${p.shots.reduce((n,s)=>n+s.count,0)}カット</span></div>${p.researchRequired?'<p class="notice">要リサーチ</p>':''}<p class="tiny">${p.actualAt?'投稿済み':p.paused?'投稿休止':blocked(p.date)?'投稿不可日':'予定'}${p.manual?' / 編集済み':''}</p><button class="secondary full" data-work-post="${p.id}">投稿内容を見る・編集</button></article>`).join('')||'<article class="card">この期間の投稿はまだありません。</article>';if(!dx('#planAxisSummary'))dx('#planList').insertAdjacentHTML('beforebegin','<article class="card" id="planAxisSummary"></article>');dx('#planAxisSummary').innerHTML='<h3>この10日間の役割</h3>'+balanceHTML(rangePosts())+`<details><summary>販売周期・月間・お客様の声</summary><p>販売直前は商品理解と販売案内、販売後は使い方・ケア・経年変化・製作背景を考慮。前回の成功だけで埋めず、新しいテーマも試します。</p>${balanceHTML(demo.posts.filter(p=>p.date.startsWith(demo.planStart.slice(0,7))))}${voiceCandidates().map(v=>`<p>${html(v.question)}<br><small>${html(v.route)}${v.confirmed?'':'（候補・未確認）'}</small></p>`).join('')}</details><details><summary>親テーマ・知識データベース</summary><p class="notice">正式100テーマを原文どおり登録。主目的は投稿ごとに決めます。66〜80は要リサーチ。</p>${['LEATHER','ANIMAL','AGING','CARE','CRAFT','INDUSTRY','FASHION','CUSTOMER'].map(g=>{const ts=OFFICIAL_TOPICS.filter(t=>t.group===g);return `<details><summary>${g} ${ts[0].number}〜${ts.at(-1).number}${g==='INDUSTRY'?' · 要リサーチ':''}</summary>${ts.map(t=>`<p class="tiny">#${String(t.number).padStart(2,'0')} ${html(t.title||'正式原文待ち')}</p>`).join('')}</details>`;}).join('')}<details><summary>派生・追加テーマ ${demo.extraThemes.length}件</summary>${demo.extraThemes.map(t=>`<p>${html(t.title)}<br><small>${html(t.status)} / ${html(t.source)}</small></p>`).join('')}</details></details>`;};
const planContentRender=renderPlan;
renderPlan=function(){planContentRender();const period=salesCycleBlock(),list=dx('#planList');if(!period||!list)return;const posts=rangePosts(),dates=Array.from({length:dayDiff(period.to,period.from)+1},(_,i)=>dayAdd(period.from,i));for(const date of dates){if(!blocked(date)||posts.some(p=>p.date===date))continue;const card=document.createElement('article');card.className='card blocked-day-card';card.innerHTML=`<span class="badge">${planDay(date)}</span><h3>投稿不可</h3>`;const index=posts.findIndex(p=>p.date>date),cards=[...list.children];if(index<0)list.append(card);else list.insertBefore(card,cards[index]);}};
const oldRenderMonth=renderMonthWork;renderMonthWork=function(){oldRenderMonth();dx('#monthSavedWork').insertAdjacentHTML('beforeend','<details><summary>今月の投稿バランス</summary>'+balanceHTML(demo.posts.filter(p=>p.date.startsWith(monthCursor)))+'</details>');};
const oldPrimary=primaryRecord;primaryRecord=function(p){if(!p.actualSnapshot)return null;return oldPrimary(p);};
const originalTaskCard=taskWorkCard;taskWorkCard=function(t){const a=actualPost(t.p);return originalTaskCard(t).replace('<p class="exact">',`<p>${html(a?.theme||t.p.theme)}</p>${!a?'<p class="tiny muted">実際の投稿内容は未確認</p>':''}<p class="exact">`);};
const oldReviewRender=renderReviewWork;renderReviewWork=function(){oldReviewRender();if(!dueTasks(reviewDate).length)dx('#todayRecordsWork').innerHTML='<h2>今日入力する投稿</h2><article class="card">'+(reviewDate===TODAY?'今日の入力はありません':'この日の入力はありません')+'</article>';};
const extraMetrics={reach:'リーチ',shares:'シェア',profile:'プロフィールアクセス'};
editRecord=function(key){const t=allTasks().find(t=>t.key===key);if(!t)return;const r=demo.records[key]||{},p=actualPost(t.p)||t.p;openForm('投稿の数字を記録',`<p>${short(jstDate(t.p.actualAt))}投稿｜${formats[p.format]}｜${t.stage==='7d'?'7d 主要評価':'24h 任意'}</p><strong>${html(p.theme)}</strong><p class="exact">${html(postLabel(p))}</p>${!t.p.actualSnapshot?`<p class="notice">実際の本文・形式を確認すると分析に使用できます。</p><button type="button" class="ghost" data-actual-edit="${p.id}">実際の投稿内容を確認</button>`:''}<div class="metrics-grid">${Object.entries(metricNames).map(([k,n])=>formInput(n,k,r[k]??'','number')).join('')}</div><details><summary>取得できた追加の数字</summary><div class="metrics-grid">${Object.entries(extraMetrics).map(([k,n])=>formInput(n,k,r[k]??'','number')).join('')}</div></details><label class="wlabel">コメント内容（1件ずつ改行）<textarea name="commentContents">${html((r.commentContents||[]).join('\n'))}</textarea></label><details><summary>反応の意味・お客様の声</summary>${Object.entries(AXES).map(([k,n])=>`<label class="wlabel">${html(n)}<textarea name="meaning-${k}" placeholder="実際の反応や気づき。未確認なら空欄">${html(r.meaning?.[k]||'')}</textarea></label>`).join('')}<label class="wlabel">DM・質問・要望（1件ずつ改行）<textarea name="voices">${html((r.voices||[]).join('\n'))}</textarea></label></details>${formInput('数字を確認した日時（日本時間）','observedAt',r.observedAt||jstInput(),'datetime-local',true)}<p class="tiny muted">空欄＝未取得、0＝確認済み0件。入力日時は保存時に記録。</p><details><summary>時点の判定（仮案）</summary><p>7dは実投稿の168時間後以上192時間未満。24hは24時間後以上48時間未満。期間外は参考として分けます。</p><p>予定 ${t.p.date} ${t.p.plannedTime}<br>実際 ${html(jstInput(t.p.actualAt))}<br>前回入力 ${r.enteredAt?html(jstInput(r.enteredAt)):'なし'}</p></details><label class="pick-name"><input type="checkbox" name="missed" ${r.missed?'checked':''}>その時点の数字を取得できなかった</label>`,f=>{const data={postId:p.id,stage:t.stage,observedAt:f.get('observedAt'),enteredAt:nowISO(),missed:f.has('missed')},at=new Date(data.observedAt+'+09:00');if(!Number.isFinite(+at)||+at>Date.now()+60000||+at<new Date(t.p.actualAt))throw Error('確認日時は実投稿以降、現在までにしてください');for(const k of Object.keys({...metricNames,...extraMetrics})){const raw=f.get(k);data[k]=raw===''?null:Number(raw);if(data[k]!==null&&(!Number.isSafeInteger(data[k])||data[k]<0))throw Error('数字は0以上の整数です');}data.commentContents=String(f.get('commentContents')).split('\n').filter(x=>x.trim());data.voices=String(f.get('voices')).split('\n').filter(x=>x.trim());data.meaning=Object.fromEntries(Object.keys(AXES).map(k=>[k,f.get('meaning-'+k)]));demo.records[key]=data;data.voices.forEach((text,i)=>{const id=key+'-voice-'+i;let v=demo.reactions.find(v=>v.id===id);if(!v){v={id,kind:'お客様の声',date:jstDate(t.p.actualAt),question:text,options:[],answers:[],dm:[],reactions:null,theme:p.theme,skuIds:[...p.skuIds],analysis:'',destinations:[],uses:[],postId:p.id,recordId:key};demo.reactions.push(v);}else v.question=text;});});};
function editActual(id){const p=demo.posts.find(p=>p.id===id),a=actualPost(p)||p;dx('#dayDialog').close();openForm('実際に投稿した内容',formInput('実投稿日時（日本時間）','actual',p.actualAt?jstInput(p.actualAt):jstInput(),'datetime-local',true)+formInput('実際のテーマ','theme',a.theme,'text',true)+formSelect('実際の形式','format',Object.entries(formats),a.format)+formSelect('主目的','primaryAxis',[['','未確認'],...Object.entries(AXES)],a.primaryAxis||'')+`<label class="wlabel">実際の本文<textarea name="caption" rows="7">${html(a.caption)}</textarea></label><details><summary>実際の商品・カラー</summary>${skuPickerWork(a.skuIds)}</details><label class="pick-name"><input type="checkbox" name="confirmed" required>実際の投稿と内容・日時を確認した</label><p class="tiny muted">予定を残し、実績を別に保存します。レビューと分析はこちらを使用します。</p>`,f=>{const at=new Date(f.get('actual')+'+09:00');if(!Number.isFinite(+at)||+at>Date.now()+60000)throw Error('現在までの実投稿日時を入力してください');p.actualAt=at.toISOString();p.actualSnapshot={theme:f.get('theme'),derivedTheme:f.get('theme'),caption:f.get('caption'),format:f.get('format'),skuIds:f.getAll('skuIds'),primaryAxis:f.get('primaryAxis')||null,parentId:a.parentId||null,topicGroup:a.topicGroup||null,takeaway:a.takeaway||'',sequence:structuredClone(a.sequence||[]),stories:structuredClone(a.stories||[]),confirmedAt:nowISO()};p.actualContentVerified=true;p.revision++;});}
const originalEditReaction=editReaction;editReaction=function(id){originalEditReaction(id);const r=demo.reactions.find(r=>r.id===id);dx('#workForm .save-foot').insertAdjacentHTML('beforebegin',formSelect('次につなげる先','route',[['','候補を見てから判断'],['情報発信','情報発信'],['商品開発候補','商品開発候補'],['両方','情報発信と商品開発']],r?.route||'')+formSelect('関連する投稿','postId',[['','未指定'],...demo.posts.filter(p=>!p.deleted).map(p=>[p.id,short(p.date)+' '+p.theme])],r?.postId||''));const save=dx('#workForm').onsubmit;dx('#workForm').onsubmit=e=>{const f=new FormData(e.target),n=demo.reactions.length;save(e);if(!dx('#workDialog').open){const target=id?demo.reactions.find(x=>x.id===id):demo.reactions[n];if(target){target.route=f.get('route')||null;target.postId=f.get('postId')||null;persist();refreshWork();}}};};
const oldResults=renderResults;renderResults=function(){oldResults();dx('#reactionListWork').insertAdjacentHTML('beforeend',`<details class="card"><summary>情報発信・商品開発につなげる</summary>${voiceCandidates().map(v=>`<p>${html(v.question)}<br><span class="badge">${html(v.route)}${v.confirmed?'':' · 候補'}</span><button class="ghost small" data-work-reaction="${v.id}">確認・編集</button></p>`).join('')||'<p>まだ声の記録はありません。</p>'}<p class="tiny muted">候補は言葉から分類した仮案です。同じ声の件数だけで開発を決定しません。</p></details>`);};
// 共用カットは明示的な参照だけ統合する。
shootGroups=function(){const groups=new Map();rangePosts().filter(p=>!p.paused&&!p.deleted&&!blocked(p.date)).forEach(p=>{const shots=[...p.shots,...p.stories.filter(s=>!s.shotId||!p.shots.some(c=>c.id===s.shotId)).map(s=>({signature:'story|'+s.asset+'|'+s.skuIds.join('|'),media:/動画/.test(s.asset)?'動画':'写真',what:s.asset,skuIds:s.skuIds,count:1}))];for(const c of shots){const k=c.signature||[c.media,c.what,...c.skuIds].join('|');if(!groups.has(k))groups.set(k,{...c,uses:[]});groups.get(k).uses.push({id:p.id,date:p.date});}});return [...groups.values()];};
function reviewActualChoice(p,f){
 const choice=f.get('reviewActualChoice');
 if(choice==='later')return null;
 if(!['planned','changed'].includes(choice))throw Error('実際の投稿内容の確認方法を選んでください');
 const actual=choice==='changed'?{theme:String(f.get('actualTheme')||'').trim(),caption:String(f.get('actualCaption')||'').trim(),format:f.get('actualFormat'),primaryAxis:f.get('actualAxis')||null,parentId:f.get('actualParent')||null,skuIds:f.getAll('skuIds')}:{theme:p.theme,caption:p.caption,format:p.format,primaryAxis:p.primaryAxis||null,parentId:p.parentId||null,skuIds:[...p.skuIds]};
 if(!actual.theme||!actual.caption||!['Feed','Reel','Carousel'].includes(actual.format))throw Error('実際のテーマ・形式・本文を確認してください');
 const parent=OFFICIAL_TOPICS.find(t=>t.id===actual.parentId);
 return {theme:actual.theme,derivedTheme:actual.theme,caption:actual.caption,format:actual.format,skuIds:actual.skuIds,primaryAxis:actual.primaryAxis,parentId:actual.parentId,topicGroup:parent?.group||p.topicGroup||null,takeaway:p.takeaway||'',sequence:structuredClone(p.sequence||[]),stories:structuredClone(p.stories||[]),cta:p.cta||'',advertised:!!demo.ads.some(ad=>ad.postId===p.id),confirmedAt:nowISO()};
}
function reviewActualRecord(key,recordForm){
 const task=allTasks().find(t=>t.key===key),post=task?.p;
 if(!post||post.actualSnapshot||task.stage!=='7d')return recordForm(key);
 const originalOpen=openForm;
 openForm=function(title,body,onSave,onDelete){
  openForm=originalOpen;
  const choices=`<fieldset class="card"><legend>実際に投稿した内容も確認</legend><p class="tiny">予定は変更しません。既存の実投稿日時と7d数値も保持します。</p><label class="pick-name"><input type="radio" name="reviewActualChoice" value="planned">予定どおり投稿した</label><label class="pick-name"><input type="radio" name="reviewActualChoice" value="changed">内容を変更して投稿した</label><label class="pick-name"><input type="radio" name="reviewActualChoice" value="later" checked>今回は数値だけ保存し、実内容は後で確認する</label><details id="reviewActualChanges"><summary>変更した実内容</summary>${formInput('実際のテーマ','actualTheme',post.theme)}${formSelect('実際の形式','actualFormat',Object.entries(formats),post.format)}${formSelect('実際の主目的','actualAxis',[['','未確認'],...Object.entries(AXES)],post.primaryAxis||'')}<label class="wlabel">実際の本文<textarea name="actualCaption" rows="6">${html(post.caption||'')}</textarea></label>${formSelect('実際の親テーマ','actualParent',[['','未指定'],...OFFICIAL_TOPICS.map(t=>[t.id,t.group+' #'+t.number+' '+t.title])],post.parentId||'')}<details><summary>実際の商品・カラー</summary>${skuPickerWork(post.skuIds)}</details></details></fieldset>`;
  originalOpen(title,body+choices,f=>{const snapshot=reviewActualChoice(post,f);const result=onSave(f);if(snapshot){post.actualSnapshot=snapshot;post.actualContentVerified=true;post.revision++;}return result;},onDelete);
  dx('#workForm fieldset.card').insertAdjacentHTML('afterbegin',`<details><summary>予定していた内容を確認</summary><p>${html(post.theme)}｜${html(formats[post.format]||post.format)}</p><p class="exact">${html(post.caption||'本文未設定')}</p><p>${html(post.skuIds.map(skuLabel).join(' ＋ ')||'商品なし')}</p></details>`);
  const form=dx('#workForm');form.elements.reviewActualChoice.forEach(input=>input.addEventListener('change',()=>{if(input.checked&&input.value==='changed')dx('#reviewActualChanges').open=true;}));
 };
 try{return recordForm(key);}finally{openForm=originalOpen;}
}
const originalPayload=analysisPayload;
analysisPayload=function(){const base=originalPayload();const raw=base.posts;return {...base,schema:2,posts:raw.filter(p=>demo.posts.find(x=>x.id===p.id)?.actualSnapshot).map(p=>{const actual=actualPost(demo.posts.find(x=>x.id===p.id));return {...p,...actual,productNames:postLabel(actual),planned:{date:p.date,format:p.format,theme:p.theme},parentTheme:topicLabel(actual)};}),unconfirmedActualPosts:raw.filter(p=>!demo.posts.find(x=>x.id===p.id)?.actualSnapshot).map(p=>({id:p.id,actualAt:p.actualAt,reason:'実際の投稿内容が未確認のため主要分析から除外'})),officialThemes:OFFICIAL_TOPICS,themeGuidance:{ANIMAL:'動物・部位・飼育環境・原皮・なめし・仕上げまで含めて違いを説明し、動物名だけで単純化しない',AGING:'購入した後までつなげる',CARE:'購入後のお客様との接点',CRAFT:'元タンナー・革職人の確認できる経験を活かす',INDUSTRY:'66〜80は投稿制作時に最新の統計・業界情報・公的資料を調査。未確認情報を事実として生成しない',FASHION:'革だけに閉じずファッションや生活とのつながりを楽しむ',CUSTOMER:'関係づくり、購入後のファン化、情報発信・サービス改善・商品開発へつなげる'},additionalThemes:demo.extraThemes,voiceCandidates:voiceCandidates(),periodBalance:axisBalance(raw.map(p=>actualPost(demo.posts.find(x=>x.id===p.id))).filter(Boolean)),monthBalance:axisBalance(demo.posts.filter(p=>p.date.startsWith(demo.planStart.slice(0,7)))),formatCohorts:Object.keys(AXES).flatMap(axis=>[...new Set(demo.posts.map(p=>actualPost(p)?.topicGroup).filter(Boolean))].map(group=>({axis,group,advertising:false,data:formatEvidence(axis,group)}))),brandPrinciples:['CUSTOMER VALUE × INSTAGRAM GROWTH × BUSINESSを同時に見る。売上は価値提供を続けるために必要','固定配分はしない。販売直前は商品・販売、販売後は購入後の利用や楽しみも検討','役立つ話だけにも商品紹介だけにも偏らせない','成功テーマをコピーし続けず、新しい発見・世界観・商品理解・販売・交流・探索を残す','正式100の原文未確認分を生成して埋めない。派生は独立IDで親へ紐づける','INDUSTRY66〜80は要リサーチ。未確認の最新数値・業界・環境情報を事実にしない','実際の投稿と確認日時を使用。未取得を0にしない。7d主要、24h補助','正式商品名は変えずIDで紐づけ。手動編集は選択なしに上書きしない','Storyは知識・参加対話・別商品発見・当日の投稿導線の4枠。返すべき反応を優先。参加型スタンプ1日1回。重複商品はBUSINESS上の理由が必要。絵文字・星占いなし']};};
function extractJsonPayload(raw){const text=String(raw||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');try{JSON.parse(text);return text;}catch{}for(const start of ['{','[']){const from=text.indexOf(start);if(from<0)continue;for(let to=text.length-1;to>from;to--){if(!'}]'.includes(text[to]))continue;const candidate=text.slice(from,to+1);try{JSON.parse(candidate);return candidate;}catch{}}}throw Error('ChatGPTの返答からJSON部分を読み取れませんでした。JSON部分のみ貼り付けてください。');}
analysisSchema=function(){const p=rangePosts().find(p=>!p.actualAt&&!p.deleted&&p.conceptVersion===2),evidence=demo.reactions[0]?.id||demo.posts[0]?.id;return {schema:2,batchId:'ここを一意の分析IDにする',period:{from:analysisFrom,to:analysisTo},facts:[{text:'実際の記録から確認できた事実',evidence:[evidence]}],trends:[],hypotheses:[{text:'まだ確定していない解釈',evidence:[evidence]}],experiments:[{category:'次回検証',text:'次に何を変え、どの主目的の反応を見るか',evidence:[evidence]}],newThemes:[],proposals:p?[{postId:p.id,expectedRevision:p.revision,evidence:[evidence],changes:Object.fromEntries(['themeId','primaryAxis','parentId','topicGroup','theme','derivedTheme','takeaway','subjects','role','format','caption','hook','cta','sequence','stories','shots','voiceIds','researchRequired'].map(k=>[k,k==='format'?(p.format==='Reel'?'Reel':'Feed'):structuredClone(p[k]??null)]))}]:[]};};
exportPrompt=function(){return `あなたはcian en paclamの編集・運用パートナーです。最上位目的は、お客様に革をもっと楽しんでもらい、困ったときには手助けし、その価値をInstagramでより多くの人へ届けながらブランドも成長することです。
CUSTOMER VALUE / INSTAGRAM GROWTH / BUSINESSを10日と販売周期で同時に考えてください。固定比率なし。売上を弱めず、役立つ投稿だけにも商品紹介だけにも偏らせないこと。
生成順序：期間の役割→主目的→確認済み親テーマ・蓄積テーマ・お客様の声→伝えること→適切な商品/革/工程/道具→形式→構成/本文/Story/撮影を一体化。販売直前は販売商品起点可。
本文はテーマに沿った長文案。未確認の製品性能、体験、統計を作らない。要リサーチは事実化せず確認事項として残す。正式100テーマは原文が確認済みのものだけ使い、追加テーマは新しいIDで区別。
事実・傾向・仮説・次に試すことを分ける。傾向は複数の独立記録IDを根拠にする。同じ投稿の24hと7dだけを複数投稿の傾向にしない。実際の投稿内容が未確認の投稿は主要分析から除外。ただし記録済みの7d/24h数値は参考事実として扱い、予定テーマ・形式・商品・本文の評価根拠に使わない。未取得・0・期間外・広告ありを分け、7dを優先。
各投稿の主目的に合わせて、保存や役立った声、認知やフォロー、商品質問や再販希望を読み取る。再生だけで成功としない。数値から売上・購入を推定しない。形式は同じ目的/テーマ/広告条件で比較し、少数では断定しない。
お客様の声を情報発信または商品開発候補へ紐づける。成功テーマを利用しつつ新しい探索、ブランド、販売を維持。次の企画に具体的に反映する。過去のCarousel実績は履歴として扱い、新しい自動提案の形式はFeed/Reelのみ。
返答は下のschema:2と同じJSONのみ。未知キー不可。newThemesは {id:"extra-一意ID",parentId:"確認済み親IDまたはnull",title:"派生/追加テーマ",group:"分類",evidence:["記録ID"]}。official-IDの新規作成は禁止。
proposalsのテーマを変える場合はprimaryAxis,parentId,topicGroup,theme,derivedTheme,takeaway,subjects,role,format,caption,hook,cta,sequence,stories,shots,voiceIds,researchRequiredを一体で返す。sequenceは{order,visual,words,shotId}。Storyは4枠（1別テーマの知識、2反応への返答を優先、3別商品発見、4今日の投稿への導線）。slot,theme,parentId,topicGroup,materialMode,combinationReason,overlapReason,reactionId,researchRequiredを必要に応じて指定。materialModeは過去素材使用可／新規撮影必要／まとめ撮り対象。shotIdは新規撮影が必要な場合のみ対応する撮影IDを参照。複数商品の変更はchanges.skuIdsとcombinationReasonを指定。商品・カラーは正確なIDで。手動編集済みは差分確認で選ばれたものだけ反映する。
\n返答形式:\n`+JSON.stringify(analysisSchema(),null,2)+'\n\n分析データ:\n'+JSON.stringify(analysisPayload(),null,2);};
validateImport=function(raw){if(raw.length>500000)throw Error('50万文字以内で貼り戻してください');let a;try{a=JSON.parse(raw)}catch{throw Error('JSONのみ貼り戻してください');}const obj=(o,keys)=>{if(!o||typeof o!=='object'||Array.isArray(o)||Object.keys(o).some(k=>!keys.includes(k)))throw Error('未対応の項目があります');},txt=(s,n=18000)=>{if(typeof s!=='string'||!s.trim()||s.length>n)throw Error('文章を確認してください');},arr=(x,n=100)=>{if(!Array.isArray(x)||x.length>n)throw Error('一覧の形式を確認してください');};obj(a,['schema','batchId','period','facts','trends','hypotheses','experiments','newThemes','proposals']);if(a.schema!==2)throw Error('今回のコピーで出力したschema:2を使用してください');txt(a.batchId,100);if(demo.analyses.some(x=>x.batchId===a.batchId))throw Error('この分析は取り込み済みです');obj(a.period,['from','to']);if(a.period.from!==analysisFrom||a.period.to!==analysisTo)throw Error('分析期間が一致しません');const available=new Set([...Object.keys(demo.records),...demo.posts.map(p=>p.id),...demo.reactions.map(r=>r.id),...demo.analyses.map(x=>x.batchId)]);const ev=e=>{arr(e);if(!e.length||e.some(id=>!available.has(id)))throw Error('根拠の記録IDが見つかりません');};for(const key of ['facts','trends','hypotheses','experiments']){arr(a[key],30);a[key].forEach(x=>{obj(x,['text','evidence','category']);txt(x.text,4000);ev(x.evidence);if(x.category&&!['伸ばす','継続','改善','次回検証'].includes(x.category))throw Error('アクション区分を確認してください');if(key==='trends'&&new Set(x.evidence.map(id=>demo.records[id]?.postId||id)).size<2)throw Error('傾向には複数の独立した記録が必要です');});}
 const parent=id=>{if(id!==null&&!OFFICIAL_TOPICS.some(t=>t.id===id&&t.verified))throw Error('確認済みの親テーマだけ使用できます');};arr(a.newThemes,30);const newIds=new Set();a.newThemes.forEach(t=>{obj(t,['id','parentId','title','group','evidence']);txt(t.id,100);if(!t.id.startsWith('extra-')||newIds.has(t.id)||demo.extraThemes.some(x=>x.id===t.id))throw Error('追加テーマIDが不正または重複しています');newIds.add(t.id);parent(t.parentId);txt(t.title,200);txt(t.group,50);ev(t.evidence);});
 arr(a.proposals,30);const ids=new Set(),bundle=['themeId','primaryAxis','parentId','topicGroup','theme','derivedTheme','takeaway','subjects','role','format','caption','hook','cta','sequence','stories','shots','voiceIds','researchRequired'];a.proposals.forEach(x=>{obj(x,['postId','expectedRevision','evidence','changes']);const p=rangePosts().find(p=>p.id===x.postId&&!p.deleted&&!p.actualAt);if(!p||ids.has(x.postId))throw Error('未投稿の対象IDを確認してください');ids.add(x.postId);if(x.expectedRevision!==p.revision)throw Error('コピー後に編集されています。再度コピーしてください');ev(x.evidence);const c=x.changes;obj(c,[...bundle,'skuIds','combinationReason']);if(c.combinationReason)txt(c.combinationReason);if(!Object.keys(c).length)throw Error('変更内容が空です');if(('theme' in c||'derivedTheme' in c||'takeaway' in c)&&bundle.some(k=>!(k in c)))throw Error('テーマ変更は本文・構成・Story・撮影を一体で提案してください');if(c.themeId&&!demo.extraThemes.some(t=>t.id===c.themeId)&&!newIds.has(c.themeId))throw Error('追加・派生テーマIDが見つかりません');if(c.primaryAxis&&!AXES[c.primaryAxis])throw Error('主目的を確認してください');if('parentId' in c)parent(c.parentId);if(c.parentId&&c.topicGroup!==OFFICIAL_TOPICS.find(t=>t.id===c.parentId)?.group)throw Error('親テーマと分類が一致しません');for(const k of ['theme','derivedTheme','takeaway','subjects','role','caption','hook','cta','topicGroup'])if(k in c)txt(c[k]);if(c.theme&&c.derivedTheme!==c.theme)throw Error('派生テーマと投稿テーマを一致させてください');if(c.format&&!['Feed','Reel'].includes(c.format))throw Error('自動形式はFeedまたはReelです');if('researchRequired' in c&&typeof c.researchRequired!=='boolean')throw Error('要リサーチの指定を確認してください');if(c.topicGroup==='INDUSTRY'&&!c.researchRequired)throw Error('INDUSTRYは要リサーチです');if(c.voiceIds){arr(c.voiceIds);if(c.voiceIds.some(id=>!demo.reactions.some(r=>r.id===id)))throw Error('お客様の声IDが不正です');}
 const validSku=list=>{arr(list,8);if(list.some(id=>!sku(id)))throw Error('商品IDが不正です');};if(c.skuIds)validSku(c.skuIds);if(c.shots){arr(c.shots,30);if(!c.shots.length)throw Error('撮影内容が必要です');const seen=new Set();c.shots.forEach(s=>{obj(s,['id','signature','media','what','skuIds','count']);txt(s.id,100);if(seen.has(s.id))throw Error('撮影IDが重複しています');seen.add(s.id);txt(s.signature,1000);txt(s.what,4000);if(!['動画','写真'].includes(s.media)||!Number.isSafeInteger(s.count)||s.count<1||s.count>20)throw Error('撮影項目が不正です');validSku(s.skuIds);});}
 if(c.sequence){arr(c.sequence,30);if(!c.sequence.length)throw Error('構成が必要です');c.sequence.forEach((s,i)=>{obj(s,['order','visual','words','shotId']);if(s.order!==i+1)throw Error('構成の順序を確認してください');txt(s.visual,4000);txt(s.words,4000);if(!(c.shots||p.shots).some(t=>t.id===s.shotId))throw Error('構成と撮影IDがつながっていません');});}
 if(c.stories){arr(c.stories,4);if(c.stories.length!==4)throw Error('Storyは基本4枠です');let polls=0;const counts={};c.stories.forEach(s=>{obj(s,['text','asset','action','purpose','skuIds','participatory','shotId','slot','theme','parentId','topicGroup','materialMode','combinationReason','overlapReason','reactionId','researchRequired','manual','kind','options','correctAnswer','researchBrief','needsAnswer']);for(const k of ['text','asset','action','purpose']){if(k==='text'&&s.researchRequired&&s[k]==='')continue;txt(s[k],4000);}if(/\p{Extended_Pictographic}/u.test(s.text)||/星占い|星座占い/.test(s.text))throw Error('Storyに絵文字・星占いは使いません');validSku(s.skuIds);if(typeof s.participatory!=='boolean')throw Error('参加型の指定が必要です');if(s.participatory)polls++;if(s.parentId)parent(s.parentId);if((s.topicGroup==='INDUSTRY'||s.topicGroup==='FASHION')&&!s.researchRequired)throw Error('業界・ニュース・トレンドは要リサーチとして扱ってください');for(const id of s.skuIds)if((c.skuIds||p.skuIds).includes(id)&&!s.overlapReason)counts[id]=(counts[id]||0)+1;if(s.shotId&&!(c.shots||p.shots).some(t=>t.id===s.shotId))throw Error('Storyの撮影IDが見つかりません');});if(polls>1||Object.values(counts).some(n=>n>1)||!c.stories.some(s=>!s.skuIds.length))throw Error('Storyの重複商品・参加回数・見る理由を確認してください');}
 });return a;};
const originalApply=applyImport;applyImport=function(){if(!pendingImport)return;const topics=structuredClone(pendingImport.newThemes||[]),batch=pendingImport.batchId;originalApply();if(demo.analyses.some(a=>a.batchId===batch)){topics.forEach(t=>demo.extraThemes.push({...t,status:t.parentId?'派生テーマ':'追加テーマ',source:batch,uses:[]}));persist();refreshWork();}};
const originalAnalysisRender=renderAnalysis;renderAnalysis=function(){originalAnalysisRender();dx('#analysisCounts').textContent=analysisPayload().posts.length+'投稿（実内容確認済み） / 実内容未確認 '+analysisPayload().unconfirmedActualPosts.length+'件 / 質問・反応 '+demo.reactions.length+'件';dx('#analysisHistoryWork').innerHTML=demo.analyses.slice().reverse().map(a=>`<details><summary>${a.period.from}〜${a.period.to} · ${a.appliedPostIds.length}投稿へ反映</summary>${[['facts','事実'],['trends','傾向'],['hypotheses','仮説'],['experiments','次に試すこと']].map(([k,n])=>`<h4>${n}</h4>${(a[k]||[]).map(x=>`<p>${html(x.text)}<br><small>根拠：${html(x.evidence.join(', '))}</small></p>`).join('')}`).join('')}</details>`).join('');};
periodSummary=function(from,to){const ps=demo.posts.filter(p=>p.actualAt&&jstDate(p.actualAt)>=from&&jstDate(p.actualAt)<=to);return ['Reel','Carousel','Feed'].map(format=>{const posts=ps.filter(p=>(actualPost(p)?.format||p.format)===format),ready=posts.map(primaryRecord).filter(Boolean),sum=k=>ready.reduce((n,r)=>n+(r[k]||0),0),views=sum('views');return {format:formats[format],posts:posts.length,complete:ready.length,pending:posts.length-ready.length,views,likes:sum('likes'),comments:sum('comments'),saves:sum('saves'),savePerView:views?sum('saves')/views:null,adPosts:posts.filter(p=>demo.ads.some(a=>a.postId===p.id)).length};});};
// 既存イベントを使う画面は維持。実投稿登録のみ、新しい実績フォームへ送る。
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.workPublish){e.stopImmediatePropagation();editActual(b.dataset.workPublish);}if(b.dataset.actualEdit){e.stopImmediatePropagation();editActual(b.dataset.actualEdit);}if(b.dataset.conceptEdit)editConcept(b.dataset.conceptEdit);},true);
const axisMetaEdit=editPostMeta;editPostMeta=function(id){axisMetaEdit(id);const form=dx('#workForm'),save=form.onsubmit;form.onsubmit=e=>{save(e);if(!dx('#workDialog').open){const p=demo.posts.find(p=>p.id===id);p.derivedTheme=p.theme;p.reviewNeeded=['本文・Story・構成とテーマのつながりを確認'];persist();refreshWork();}};};
const confirmedAnalysisPayload=analysisPayload;
analysisPayload=function(){
 const data=confirmedAnalysisPayload();
 const actualIds=new Set([...data.posts,...data.unconfirmedActualPosts].map(p=>p.id));
 const previousAnalyses=(data.previousAnalyses||[]).filter(a=>a.period?.from<=data.period.to&&a.period?.to>=data.period.from||[...(a.facts||[]),...(a.trends||[]),...(a.hypotheses||[]),...(a.experiments||[])].some(x=>(x.evidence||[]).some(id=>actualIds.has(id)||actualIds.has(String(id).split('|')[0]))));
 return {...data,previousAnalyses,unconfirmedActualPosts:data.unconfirmedActualPosts.map(entry=>{
  const referenceRecords=allTasks().filter(t=>t.p.id===entry.id).flatMap(t=>{const r=demo.records[t.key];if(!r)return [];const values=Object.fromEntries(Object.keys(RESULT_METRICS).map(k=>[k,r[k]??null]));return [{key:t.key,postId:entry.id,stage:t.stage,observedAt:r.observedAt||null,captureBand:captureBand(t,r),recordState:recordState(t),values}];});
  return {...entry,referenceRecords,advertised:!!demo.ads?.some(a=>a.postId===entry.id),reason:'実投稿内容未確認。数値は参考記録とし、予定のテーマ・商品・本文へ紐づけて評価しない'};
 })};
};
// 企画は一度だけ移行。編集済みと投稿実績は一切再生成しない。
migrateConcepts();
document.head.insertAdjacentHTML('beforeend','<style>.takeaway{border-left:3px solid #495c58;padding:10px 12px;background:#f0f2ef}.stories-always{margin:20px 0}.stories-always .story-card{margin:10px 0;padding:14px;border:1px solid #d8d8d3;border-radius:12px}.axis-counts{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.axis-counts>div{padding:10px 6px;background:#f0f2ef;border-radius:10px;text-align:center}.axis-counts strong{font-size:22px;display:block}.axis-counts small{display:block;font-size:12px}.concept-detail{margin:12px 0}#planAxisSummary p{line-height:1.65}.wlabel textarea{width:100%;box-sizing:border-box}</style>');
persist();refreshWork();
const basePreviewImport=previewImport;previewImport=function(){basePreviewImport();if(pendingImport)dx('#importPreview').insertAdjacentHTML('afterbegin',`<details open><summary>分析と追加テーマを確認</summary>${[['facts','事実'],['trends','傾向'],['hypotheses','仮説'],['experiments','次に試すこと']].map(([k,label])=>`<h4>${label}</h4>${pendingImport[k].map(x=>`<p>${html(x.text)}<br><small>根拠：${html(x.evidence.join(', '))}</small></p>`).join('')||'<p>記録なし</p>'}`).join('')}${pendingImport.newThemes.length?'<h4>正式100とは別に保存するテーマ</h4>'+pendingImport.newThemes.map(t=>`<p>${html(t.title)}<br><small>${html(t.parentId||'親テーマ未指定')}</small></p>`).join(''):''}</details>`);};
const importedApply=applyImport;applyImport=function(){const batch=pendingImport?.batchId;importedApply();const a=demo.analyses.find(a=>a.batchId===batch);if(a){for(const id of a.appliedPostIds){const p=demo.posts.find(p=>p.id===id);for(const rid of p.voiceIds||[]){const r=demo.reactions.find(r=>r.id===rid);if(r&&!r.uses.some(u=>u.postId===id&&u.analysisId===batch))r.uses.push({date:p.date,note:p.theme,postId:id,analysisId:batch});}const topic=demo.extraThemes.find(t=>t.id===p.themeId);if(topic&&!topic.uses.some(u=>u.postId===id))topic.uses.push({postId:id,date:p.date});}persist();refreshWork();}};
