// 表示と操作の意味を統一。保存データは変更しない。
cycleDay=function(date){const dates=Object.values(demo.months).map(m=>m.date).filter(Boolean);if(dates.includes(date))return '販売';const last=dates.filter(d=>d<date).sort().at(-1);return last?'Day '+dayDiff(date,last):'Day未定';};
const clarityPicker=skuPickerWork;skuPickerWork=function(selected=[],statusEditing=false){const holder=document.createElement('div');holder.innerHTML=clarityPicker(selected,statusEditing);if(!statusEditing)return holder.innerHTML;const root=holder.querySelector('.picker');root.dataset.monthSalePicker='true';for(const row of root.querySelectorAll('.picker-sku')){const label=row.querySelector('.pick-name'),checkbox=label.querySelector('input'),name=document.createElement('p');name.className='exact sku-formal-name';name.textContent=label.textContent;label.replaceChildren(checkbox,document.createTextNode('今月販売する'));label.classList.add('sale-membership');checkbox.setAttribute('aria-label',name.textContent+'を今月販売する');row.prepend(name);const status=row.querySelector('[data-inline-status]');const heading=document.createElement('label');heading.className='wlabel status-heading';heading.textContent='現在の販売状態';status.id='current-sale-status-'+checkbox.value;heading.htmlFor=status.id;status.closest('.row').before(heading);}for(const button of root.querySelectorAll('[data-pick-work-all]'))button.textContent='表示中の商品を今月販売に一括追加';return holder.innerHTML;};
// 「追加」は何度押しても選択解除しない。他の用途の選択UIには影響させない。
document.addEventListener('click',e=>{const button=e.target.closest('[data-pick-work-all]');if(!button?.closest('[data-month-sale-picker]'))return;e.stopImmediatePropagation();const root=button.closest('.picker');const inputs=[...button.closest('.picker-item').querySelectorAll('.picker-sku:not([hidden]) [name=skuIds]')];inputs.forEach(input=>input.checked=true);root.querySelector('.pick-count').textContent=root.querySelectorAll('[name=skuIds]:checked').length+'SKU選択';inputs[0]?.dispatchEvent(new Event('change',{bubbles:true}));},true);
const clarityMonth=renderMonthWork;renderMonthWork=function(){clarityMonth();for(const cell of dax('#monthWorkCalendar [data-work-date]')){const label=cycleDay(cell.dataset.workDate);cell.setAttribute('aria-label',cell.getAttribute('aria-label')+' '+label);if(label==='販売')continue;const day=document.createElement('small');day.className='calendar-cycle-day';day.textContent=label;cell.querySelector('strong').after(day);}for(const small of dax('#monthSavedWork .priorityline > small'))small.textContent='今月の販売区分：'+small.textContent;};
const clarityTaskCard=taskWorkCard;taskWorkCard=function(t){const markup=clarityTaskCard(t),holder=document.createElement('div');holder.innerHTML=markup;const head=holder.querySelector('h3'),p=actualPost(t.p)||t.p;head.textContent='対象投稿：'+planDay(jstDate(t.p.actualAt))+'｜'+formats[p.format];return holder.innerHTML;};
const clarityRecord=editRecord;editRecord=function(key){clarityRecord(key);const t=allTasks().find(t=>t.key===key);if(!t)return;const p=actualPost(t.p)||t.p;const line=dx('#workForm > p');if(line)line.textContent='対象投稿：'+planDay(jstDate(t.p.actualAt))+'｜'+formats[p.format]+'｜'+(t.stage==='7d'?'7d 主要評価':'24h 任意');};
document.head.insertAdjacentHTML('beforeend','<style>.sku-formal-name{font-weight:700;margin:8px 0 2px;overflow-wrap:anywhere}.sale-membership{font-size:14px;gap:8px}.status-heading{font-size:14px;margin:10px 0 4px}.sale-line-options .wlabel{font-size:14px}.calendar-cycle-day{font-size:12px!important;line-height:1.4!important;white-space:nowrap;color:#384c46}#monthWorkCalendar button{height:auto;min-height:96px;display:flex;flex-direction:column;align-items:center;justify-content:flex-start;gap:3px;padding:8px 2px}#monthWorkCalendar button strong{font-size:16px}.picker [data-pick-work-all]{white-space:normal;text-align:left;font-size:14px}</style>');
refreshWork();
